### ISSUE TITLE
Console friendly commands

### ISSUE THREAD

**Issue by xtomyserrax** [RoinujNosde/SimpleClans#10]
Make more commands console friendly. Many of them such as disband, roster, profile, lookup, could also be used in console, that would be amazing!

Thanks :D

**Comment by RoinujNosde** [comment]
Implementing Aikar's commands will take care of this.
marcelo-mason/SimpleClans#604

**Comment by FireController1847** [comment]
I'd love to have the ability to create clans via console. It'd allow me to use third-party APIs or whatnot to create them. Maybe something like /clan create <tag> <name> <owner>?
