### ISSUE TITLE
New permissions for ranks

### ISSUE THREAD

**Issue by xtomyserrax** [RoinujNosde/SimpleClans#101]
Add this new permissions:
- trusted: if you have this permission, you automatically will have the trusted status (or bigger if you did have)
- leader: if you have this permission, you automatically will have the leader status (or bigger if you did have)

This is a really amazing feature, nowadays you can create ranks but you also need to change status (idk if ranks win status but could be a nice touch I guess ¿?)

Maybe this suggestion is useless haha

**Comment by RoinujNosde** [comment]
> idk if ranks win status but could be a nice touch I guess 

Leaders have access to some commands that ranks don't (disband, promote, etc)
Ranks can have more, the same or less permissions than those of the trusted status.

**Comment by xtomyserrax** [comment]
Got ya. Yeah beucase it sometimes feel weird if you get for example a coleader rank but in status you stull have not-trusted haha

**Comment by RoinujNosde** [comment]
I see.
Instead of adding these two permissions, wouldn't it be better to add a new status?
Maybe "Status: in a rank".

**Comment by xtomyserrax** [comment]
That could be a cool idea, or the status just say the rank name. What if trusted, nottrusted and leader are just default ranks made by SimpleClans? That would change a lot of features though such as promoting/demoting haha

**Comment by RoinujNosde** [comment]
> or the status just say the rank name. 

Then you would have the rank name twice. On "Rank:" and "Status:".
I could remove the "Rank:" line, but some people could be using it just for the display name and trusted/leader for permissions.


> change a lot of features

~~do you mean break? haha~~

**Comment by xtomyserrax** [comment]
Yeah idk what could we do. I mean players could have their ranks and also be promoted to trusted etc

**Comment by RoinujNosde** [comment]
I think displaying "in rank" if the player is in a rank (of course) and is not trusted/leader is easier to implement. And will get rid of that oddity "co-leader" and "not trusted".
