### ISSUE TITLE
Add Support for Hexadecimal/RGB Colors

### ISSUE THREAD

**Issue by FireController1847** [RoinujNosde/SimpleClans#103]
**Is your feature request related to a problem? Please describe.**

I cannot use the 1.16 color codes.

**Describe the solution you'd like**

As with the release of 1.16, it adds support for hexadecimal color codes. It would be very nice if we were able to use these in clans for their names.

**Describe alternatives you've considered**

There are none.

**Additional context**

N/A

**Comment by RoinujNosde** [comment]
Can you refresh my memory on why hex colors don't work? I think it has something to do with the tag size.

**Comment by FireController1847** [comment]
Since the merge of #104 technically I do not believe there are any internal limitations as to why it does not support hexadecimal colors. Using 104's code I got quite a few hex code colored tags to work fine.

I think the difference is, Mojang specifies a shortcut format that can be based with Bungeecord's Chat color class: &#FFFFFF. Of course this is preferred over writing &x&F&F&F&F&F&F. When using the `ChatColor#of` method, then subsequently using `ChatColor#toString`, it converts from the shortcut format to the proper format.

Honestly now with 104 merged, it's really up to you whether or not to support the shortcut format, or to call it good how it is and use the long format :)

**Comment by RoinujNosde** [comment]
Thanks for the info.
I will make a utility class to parse the shortcut format (and also add it to strip colors).

And the db code should probably be updated to increase the size of the column `color_tag`. Its current size is 25.

**Comment by FireController1847** [comment]
My apologies if my replies weren't up to my expectations. I responded at 3:30 in the morning haha.

Here's the code that I use to parse color codes and subsequently make a new clan:
```java
net.md_5.bungee.api.ChatColor color;
try {
    color = net.md_5.bungee.api.ChatColor.of(args[2].toUpperCase());
} catch (IllegalArgumentException e) {
    sender.sendMessage("Invalid color!");
    return true;
}

// ...

this.simpleClans.getClanManager().createClan(player, color.toString() + tag, name);
```

This is, of course, if you are only directly parsing a color code string. I'm sure there's some regex out there that could identify the new formatting of strings, but I wanted to provide this to you in case it helps at all.

In terms of the `color_tag`, an increase to 30 or 35 may be a good idea due to the extra characters taken by the longer hexadecimal formatting :)

**Comment by FireController1847** [comment]
I just remembered, I have another plugin that actually matches hex codes and handles them. I used one [posted in the Spigot community](https://www.spigotmc.org/threads/hex-color-code-translate.449748/#post-3867795).

Here's the method:
```java
// Hex Pattern
public static final Pattern HEX_PATTERN = Pattern.compile("&#(\\w{5}[0-9A-Fa-f])");

// Utility method to translate hex codes to color codes
// Special thanks to the Spigot community!
// https://www.spigotmc.org/threads/hex-color-code-translate.449748/#post-3867795
public static String translateHexCodes(String text) {
    Matcher matcher = HEX_PATTERN.matcher(text);
    StringBuffer buffer = new StringBuffer();
    while (matcher.find()) {
        matcher.appendReplacement(buffer, net.md_5.bungee.api.ChatColor.of("#" + matcher.group(1)).toString());
    }
    return ChatColor.translateAlternateColorCodes('&', matcher.appendTail(buffer).toString());
}
```
I use a similar method to strip color codes:
```java
// Utility method to strip hex codes
public static String stripHexCodes(String text) {
    Matcher matcher = HEX_PATTERN.matcher(text);
    StringBuffer buffer = new StringBuffer();
    while (matcher.find()) {
        matcher.appendReplacement(buffer, "");
    }
    return ChatColor.stripColor(matcher.appendTail(buffer).toString());
}
```

This method also parses and strips other colors such as &a and &f because we use ChatColor#translateAlternateColorCodes and ChatColor#stripColor

Hopefully this can help you in making your utility method :)

**Comment by RoinujNosde** [comment]
Thanks, that's definitely going to help!
