### ISSUE TITLE
More staff features

### ISSUE THREAD

**Issue by xtomyserrax** [RoinujNosde/SimpleClans#11]
I just noticed that:
- Staff cant use /clan profile to non verified clans ; I guess that staff should be able to avoid this restriction to see info about that clan
- The same with /clan roster
- It would be amazing to have a /clan list command but for non verified clans

**Comment by xtomyserrax** [comment]
So with the GUI I dont have this non verified clan issues, but if I use commands I do (for checking roster or profile while being a staff member)

**Comment by RoinujNosde** [comment]
!Check if the issuer has the bypass permission on the condition "verified".
