### ISSUE TITLE
Clan improvements/upgrades

### ISSUE THREAD

**Issue by RoinujNosde** [RoinujNosde/SimpleClans#112]
Paying to unlock features

- More than one home
- More members
- Virtual chests
- Max balance in clan bank

**Comment by SrBedrock** [comment]
- Virtual Chests

**Comment by TomLewis** [comment]
An enderchest for Clans would be amazing.

**Comment by dimon0230ru** [comment]
Clans need to add upgrades, level, and experience

**Comment by dimon0230ru** [comment]
and still capture points

**Comment by RoinujNosde** [comment]
> Clans need to add upgrades

What kind of upgrades?

**Comment by dimon0230ru** [comment]
> What kind of upgrades?

Increasing the number of participants for example

**Comment by RoinujNosde** [comment]
> Increasing the number of participants for example

That has been suggested already

**Comment by dimon0230ru** [comment]
> That has been suggested already

Or maybe you want to create a Point Capture? Became a point, with a delay of 5 seconds, for example, waited and the point is captured, now you can walk run anywhere and the point will be captured and make a profit every minute until someone becomes on it and does not capture the same

**Comment by RoinujNosde** [comment]
> Or maybe you want to create a Point Capture? Became a point, with a delay of 5 seconds, for example, waited and the point is captured, now you can walk run anywhere and the point will be captured and make a profit every minute until someone becomes on it and does not capture the same

This issue is for stuff clan leaders can buy to improve their clans.
Open another issue for unrelated suggestions.

**Comment by SrBedrock** [comment]
- Maximum amount that can be deposited in the bank of the clans, being able to give updrade to increase the maximum value.

**Comment by TomLewis** [comment]
I too run into an issue with infinite money in crew-banks this week, let us limit the maximum balance a crew bank can have!
