### ISSUE TITLE
Kills are not counted and KDR does not change

### ISSUE THREAD

**Issue by Hexagon-Dev** [RoinujNosde/SimpleClans#113]
Hello, don't know why but kills are not counted and KDR does not go up. Tried to set permission simpleclans.other.kdr-exempt to false but it does nothing. I'm using LuckPerms for permissions.

 - Server version: Paper 1.16.2
 - Plugin version: 2.14.5

Here is config:
settings:
  enable-gui: true
  disable-messages: false
  tameable-mobs-sharing: false
  teleport-blocks: false
  teleport-home-on-spawn: false
  drop-items-on-clan-home: false
  keep-items-on-clan-home: false
  item-list: []
  show-debug-info: true
  mchat-integration: false
  enable-auto-groups: false
  chat-compatibility-mode: true
  rival-limit-percent: 50
  use-colorcode-from-prefix-for-name: true
  display-chat-tags: true
  unrivable-clans:
  - admin
  - staff
  - mod
  show-unverified-on-list: false
  blacklisted-worlds: []
  banned-players: []
  disallowed-tags:
  - vip
  - clan
  language: ru_RU
  user-language-selector: false
  disallowed-tag-colors:
  - '4'
  - c
  server-name: Hex-Craft Classic
  new-clan-verification-required: true
  allow-regroup-command: true
  allow-reset-kdr: true
  rejoin-cooldown: 5
  rejoin-cooldown-enabled: true
  accept-other-alphabets-letters-on-tag: false
  ranking-type: DENSE
  list-default-order-by: kdr
  lore-length: 36
clan:
  homebase-teleport-wait-secs: 10
  homebase-can-be-set-only-once: true
  min-size-to-set-rival: 3
  max-length: 25
  max-description-length: 120
  min-description-length: 10
  max-members: 25
  confirmation-for-promote: false
  trust-members-by-default: false
  confirmation-for-demote: false
  percentage-online-to-demote: 100.0
  ff-on-by-default: false
  min-length: 2
  max-alliances: -1
  min-size-to-set-ally: 3
  min-to-verify: 1
economy:
  creation-price: 5000.0
  purchase-clan-create: true
  verification-price: 25000.0
  purchase-clan-verify: true
  invite-price: 0.0
  purchase-clan-invite: false
  home-teleport-price: 5.0
  purchase-home-teleport: false
  home-teleport-set-price: 5.0
  purchase-home-teleport-set: false
  home-regroup-price: 5.0
  purchase-home-regroup: false
  unique-tax-on-regroup: true
  issuer-pays-regroup: true
  money-per-kill: true
  money-per-kill-kdr-multipier: 2
  purchase-reset-kdr: true
  reset-kdr-price: 10000.0
  purchase-member-fee-set: false
  member-fee-set-price: 1000.0
  member-fee-enabled: false
  member-fee-last-minute-change-interval: 8
  max-member-fee: 200.0
  upkeep: 200.0
  upkeep-enabled: false
  multiply-upkeep-by-clan-size: false
  charge-upkeep-only-if-member-fee-enabled: true
purge:
  inactive-player-data-days: 30
  inactive-clan-days: 14
  unverified-clan-days: 3
request:
  message-color: b
  ask-frequency-secs: 60
  max-asks-per-request: 1440
page:
  untrusted-color: '8'
  clan-name-color: b
  subtitle-color: '7'
  headings-color: '8'
  trusted-color: f
  leader-color: '4'
  separator: '-'
  size: 100
bb:
  color: e
  accent-color: '8'
  show-on-login: true
  size: 6
  login-size: 6
commands:
  more: more
  ally: ally
  clan: clan
  accept: accept
  deny: deny
  global: global
  clan_chat: .
  force-priority: true
tag:
  default-color: '8'
  max-length: 5
  min-length: 2
  separator:
    color: '8'
    leader-color: '4'
    char: ' .'
  bracket:
    color: '8'
    leader-color: '4'
    left: ''
    right: ''
allychat:
  enable: true
  format: '&b[Альянс] &4<%clan%&4> <%nick-color%%player%&4> %rank%: &b%message%'
  rank: '&f[%rank%&f]'
  leader-color: '4'
  trusted-color: f
  member-color: '7'
clanchat:
  enable: true
  tag-based-clan-chat: false
  announcement-color: e
  format: '&b[%clan%&b] %nick-color%%player% %rank%: &b%message%'
  rank: '&f[%rank%&f]'
  leader-color: '4'
  trusted-color: f
  member-color: '7'
tasks:
  collect-fee:
    hour: 1
    minute: 0
  collect-upkeep:
    hour: 1
    minute: 30
  collect-upkeep-warning:
    hour: 12
    minute: 0
kill-weights:
  rival: 2.0
  civilian: 0.1
  neutral: 1.0
  deny-same-ip-kills: false
mysql:
  username: ''
  host: localhost
  port: 3306
  enable: false
  password: ''
  database: ''
permissions:
  auto-group-groupname: false
  YourClanNameHere:
  - test.permission
performance:
  save-periodically: true
  save-interval: 10
  use-threads: true
  use-bungeecord: false
kdr-grinding-prevention:
  enable-max-kills: true
  max-kills-per-victim: 5
  enable-kill-delay: true
  delay-between-kills: 2
safe-civilians: false

**Comment by RoinujNosde** [comment]
Are both players in clan and both clans are verified?

**Comment by Hexagon-Dev** [comment]
No, one player in clan and another is not. The player in clan kills default guy that's not in clan. Few weeks ago we did a battle of clans and both clans were verified, after some kills KDR stayed zero. Kill counter did the same.

**Comment by RoinujNosde** [comment]
/lp check <player> simpleclans.other.kdr-exempt

Run this command on both players.

**Comment by Hexagon-Dev** [comment]
Runned it, both players have simpleclans.other.kdr-exempt false
![image](https://user-images.githubusercontent.com/69513821/103168713-920a6f00-4846-11eb-9c83-18519c7f49e2.png)

**Comment by RoinujNosde** [comment]
Run /clan mostkilled and show me the result, please.

**Comment by Hexagon-Dev** [comment]
It says no kills
![image](https://user-images.githubusercontent.com/69513821/103168843-e8c47880-4847-11eb-80d1-d014337caa3e.png)

**Comment by Hexagon-Dev** [comment]
Wait, it checks kills of my own clan?
Nvm, i tried to kill to and executed command after it as a result i have the same respond: no kills.

**Comment by RoinujNosde** [comment]
Try disabling max-kills and kill-delay, restart your server and test.

**Comment by Hexagon-Dev** [comment]
Thanks! That worked.
