### ISSUE TITLE
Clan verify says its already verified when apparently not

### ISSUE THREAD

**Issue by xtomyserrax** [RoinujNosde/SimpleClans#114]
Basicly or the display is working bad or clan verify is. Check in the video how it says that the clan is unverified but when I try to verify it it says it has already been verified: https://imgur.com/RkcDiOY

Thank you for everything!

**Comment by RoinujNosde** [comment]
What's SimpleClans' version?

**Comment by xtomyserrax** [comment]
Hey, version 2.14.5
This happens only with some clans, idk the reason.
I sadly wont be able to send you the .db file :(

**Comment by RoinujNosde** [comment]
I think I know what's up.
I've moved some staff commands to "mod".
So to verify use /clan mod verify <tag>.

And I forgot to update the staff GUI with the new subcommand...
