### ISSUE TITLE
Essentials /back integration

### ISSUE THREAD

**Issue by jasonriv** [RoinujNosde/SimpleClans#118]
**Is your feature request related to a problem? Please describe.**
With essentials, you can use /back to return to your previous location after teleporting with a command such as /tpa or /home. /back does not return you to your previous location after using /clan home

**Describe the solution you'd like**
The /back command in essentials will teleport you to your previous location after using /clan home

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by RoinujNosde** [comment]
Hello,
Did you try giving the permission "essentials.back.onteleport"?
