### ISSUE TITLE
Improve clan list

### ISSUE THREAD

**Issue by xtomyserrax** [RoinujNosde/SimpleClans#12]
What if /clan list instead of saying Total Clans, says Verified Clans and Non-verified Clans?

![image](https://user-images.githubusercontent.com/6054192/87887218-885c2000-c9f9-11ea-9c3c-56491fedccd7.png)

And yeah following what I suggested in #11 , we could add another parameter to say if we want to list all types of clans, just verified ones or just non verified ones ¿? ; Idk if this would break everything

**Comment by RoinujNosde** [comment]
There is a request for a GUI frame listing the unverified clans and leftclicking would verify them. What do you think?

**Comment by xtomyserrax** [comment]
That could be cool! Or well the future staff GUI frame could have it. So when you click a clan then you go to a similar menu actual clans have, so staff could press verify there. As you prefer
