### ISSUE TITLE
Logging all /clan bank actions 

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#123]
I had a user tell me that they withdrew 20k from their crew but as they were near the max balance in Essentials Eco that the money disappeared. 
The closest I have come to a log is in the logs I can see:
```
[23:49:00] [Server thread/INFO]: GUNNAWUNNAH issued server command: /crew bank withdraw 20000
[23:49:00] [Server thread/INFO]: [Crew Announce] [GUNNAWUNNAH&4 »&r] * 20,000 $ were withdrawn
```
So first of all, I think there's a bug where, when withdrawing from a clan bank its not checking if the player will reach their max balance.

Secondly, there is no way to easily look over a log for economy with crew money being deposited and withdrawn! Essentails has a trade.log, it would be nice if it was just added to this.
But might make more sense to have your own bank log.

A better option would be to have `packed_bb` bulletin board as its own table for logging all actions, then we have a full searchable history of whats happened with a crew with timestamps, you could have a column which is a category and have bank actions possible to be queried.

Then you open up many more options in-game for crews to see a history of who took what money and when.

**Comment by RoinujNosde** [comment]
It does make sense to have a bank log.
Maybe files would be easier to browse. One file per day.

About this bug where the the max balance isn't checked, if it is in fact a bug, it seems to be on the economy plugin's part.
SimpleClans checks the success of the transaction before withdrawing the money from the bank.
So maybe your eco plugin returned a success when it shouldn't.

**Comment by TomLewis** [comment]
It's EssentialsX, so not just any old random Eco plugin. Are you using vault? 
I cant even diagnose what actually happened as there is no log! Not in EssentialsX Trade.log, not in SimpleClans, not in Vault! Nothing! Nothing logged it! So I cant even confirm it happened.

Because I have literally no idea how I would even start with diagnosing this, could you load up EssentialsX with max bal and see if you can debug what happens if you withdraw from a Clan bank if you are close to max bal? 
Or if you can tell me a way I can toggle debug for Vault/EssX eco so I can do it again on my test server to see whats actually happening in this scenario.

In Ess config.yml its
```
# Set the maximum amount of money a player can have.
# The amount is always limited to 10 trillion because of the limitations of a java double.
max-money: 250000
```

Log wise, even one big log is fine, then we can search it all in one go. Its much harder to search and parse lots of individual files, when you are looking for errors over a time period.
If you could make it record in a known format like CSV, then I could then import it myself or use it with my own scripts to parse data, so something like JSON or even CSV.
JSON has the benefit of easily being imported later on, or even parsing yourself if you ever want to use the data later on.

**Comment by RoinujNosde** [comment]
I just checked Vault and Essentials code.
The only debug option is the log file you mentioned.

And I think I found the problem:
Vault handles Essentials eco hook internally.
Essentials has a MaxMoneyException, but Vault doesn't know about it because it's suppressed by Essentials itself.

So even if the max money is exceeded, Vault will return success.


To confirm if the max money is really the problem (I think it is), set your balance to Essentials' max and try to withdraw something from the clan bank. It doesn't even have to be from the clan, just "earn" some money, this bug should happen with every plugin connecting to Vault.

**Comment by TomLewis** [comment]
Right, could you please make a hook for MaxMoneyException if the server has Essentials installed please. Quick fix! 99% of servers that have money will be using EssentialsX. 

Then logging all transactions and we should be able to keep a trail of the naughty things players manage to do!

edit: No idea why I wrote brew in the title, maybe I was thinking Crew and spelt it wrong.

**Comment by RoinujNosde** [comment]
Didn't realize it was brew haha

Anyway, you should really report this to Vault or EssentialsX. As this doesn't happen only with SimpleClans.

Their options:
1. Essentials should propagate that and Vault catch it.
2. Vault itself can check for the max money.
