### ISSUE TITLE
Problem with auto-group

### ISSUE THREAD

**Issue by xXimuS** [RoinujNosde/SimpleClans#141]
I turn auto-group-groupname and enable-auto-groups to true and in LuckPerms I created groups SCLeader, SCTrusted, SCUntrusted, but when a clan is created, the player is declared trusted or vice versa, the group does not change. I tried to name groups like these: SCLeader, Leader, SC_Leader. But still nothing works.
LuckPerms v5.2.76
SimpleClans v2.14.7
Yatopia v1.16.5-33
MC v 1.16.5
Thanks in advance :3

**Comment by RoinujNosde** [comment]
sc_leader
sc_untrusted
sc_trusted

Those are the correct groups.
They are applied when the player joins the server.

**Comment by xXimuS** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/80347443/110506645-f465d280-8107-11eb-8a3e-e380974ec5e5.png)

**Comment by xXimuS** [comment]
I have no other groups other than default.

**Comment by xXimuS** [comment]
No, I'll install it now.

**Comment by xXimuS** [comment]
I installed it, but it still doesn't work.

**Comment by xXimuS** [comment]
Yes.

**Comment by RoinujNosde** [comment]
![image](https://user-images.githubusercontent.com/6441328/110509012-6a564380-80e0-11eb-8e6b-df0d8cb672a0.png)
Just tested and it's working.

Run `/lp user <your nick> info` and post the result.

**Comment by xXimuS** [comment]
May I ask you what is your core?

**Comment by RoinujNosde** [comment]
I tested on Tuinity 1.16, but it shouldn't matter.

Let me see your config for SimpleClans and the result of that command.

**Comment by xXimuS** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/80347443/110513418-df407200-810e-11eb-8eea-f583a3a8878a.png)

**Comment by xXimuS** [comment]
[config.zip](https://github.com/RoinujNosde/SimpleClans/files/6110410/config.zip)

**Comment by RoinujNosde** [comment]
I noticed that your config begins with `wsettings:`.
It should be `settings:`

**Comment by xXimuS** [comment]
Ohhh, that really helped. Forgive me for disturbing you because of such stupidity. Can I thank you somehow? Send money for example?

**Comment by RoinujNosde** [comment]
It happens! Haha

You can donate here: https://bit.ly/donate_rj
