### ISSUE TITLE
Limitation for making wars

### ISSUE THREAD

**Issue by Tomut0** [RoinujNosde/SimpleClans#159]
How about giving an access to make a war only if amount of clan members (online/offline) equals or more than value in config? 
It should works like, the leader issued the command then get the message: 
`Your clan is too small to make wars! Required: 10 players!`

**Comment by RoinujNosde** [comment]
It could also be based on both clans sizes.
To prevent a clan with 100 members attacking one with 10.

**Comment by Tomut0** [comment]
> 
> 
> It could also be based on both clans sizes.
> To prevent a clan with 100 members attacking one with 10.

Another way is to comparing clans by KDR.
And if the one has a huge domination -> don't allow it.

**Comment by RoinujNosde** [comment]
> 
> 
> > It could also be based on both clans sizes.
> > To prevent a clan with 100 members attacking one with 10.
> 
> Another way is to comparing clans by KDR.
> And if the one has a huge domination -> don't allow it.

What if I am alone in my clan with 100 KDR and the other clan has 100 members and 100 KDR?

**Comment by Tomut0** [comment]
> 
> 
> > > It could also be based on both clans sizes.
> > > To prevent a clan with 100 members attacking one with 10.
> > 
> > 
> > Another way is to comparing clans by KDR.
> > And if the one has a huge domination -> don't allow it.
> 
> What if I am alone in my clan with 100 KDR and the other clan has 100 members and 100 KDR?

Let's leave my mind for a while

**Comment by Tomut0** [comment]
#166
