### ISSUE TITLE
PlayerInteractEvent or BlockBreakEven Console Error

### ISSUE THREAD

**Issue by Hazugg** [RoinujNosde/SimpleClans#161]
I keep getting the same error message on the console

![image](https://user-images.githubusercontent.com/31551514/113209124-4518a900-9238-11eb-9d65-df626171c321.png)

![image](https://user-images.githubusercontent.com/31551514/113209083-37632380-9238-11eb-84d3-8fd5bf2f7dae.png)

**Comment by RoinujNosde** [comment]
Fixed on the dev builds:
https://ci.codemc.io/job/RoinujNosde/job/SimpleClans/job/Dev/lastSuccessfulBuild/artifact/target/SimpleClans.jar
