### ISSUE TITLE
Clan Home teleporting player to surface from a cave

### ISSUE THREAD

**Issue by Sketsi** [RoinujNosde/SimpleClans#164]
**Describe the bug**

**To Reproduce**
1. gm3 into a cave/ravine
2. /clan set home
3. move away and run /clan home
4. teleported to surface

**Expected behavior**
I expect to be teleported to the location I set the clan home at. I set the home inside of a ravine and it teleports me to above surface.

**Screenshots**
Set clan home here:
http://prntscr.com/1113l0h
Where I end up:
http://prntscr.com/1113jvq

**Software (please complete the following information):**
 - Server: Paper 1.16.4
 - Plugin version 2.14.3-latest

**Additional context**
If I place blocks in a 2x2x3 and break them, the clan home will go to the desired location.

**Comment by Sketsi** [comment]
// Set Clan Home: https://prnt.sc/1113qub 
// Use Clan Home: https://prnt.sc/1113r40
// Version of Plugin & Server: http://prntscr.com/1113rit

**Comment by RoinujNosde** [comment]
Thanks for reporting! 
This was an interesting bug. The plugin was checking for AIR to know if it's safe to teleport; the thing is, caves have a different kind of AIR (CAVE_AIR). So it was always "unsafe".
Anyway, fixed on the latest build: https://ci.codemc.io/job/RoinujNosde/job/SimpleClans/job/Dev/
