### ISSUE TITLE
Give a permission to staff to change player's rank

### ISSUE THREAD

**Issue by Tomut0** [RoinujNosde/SimpleClans#170]
That's weird that only leaders may change player's rank. :eyes:
I want to have a command for, I guess, moderators: `/clan mod rank <clan> <player> <rank>`.

**Comment by RoinujNosde** [comment]
Why?
Ranks are managed by clan leaders.

**Comment by Tomut0** [comment]
> 
> 
> Why?
> Ranks are managed by clan leaders.

I'm a server owner and can't change ranks? 👺

**Comment by Tomut0** [comment]
No demand for the feature at this moment.
