### ISSUE TITLE
Withdrawing from the Crew bank with close to maximum balance wipes all money.

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#171]
**Describe the bug**
In Essentials that runs my Eco I have `max-money` sent to 250,000, I had a player with 30,000 already and they withdrew 240000 from their crew balance, Instead of telling the user this would be over their maximum balance, SimpleClans just deleted the money all together.

**To Reproduce**
1. Set max-money in Essentails to 250000
2. Give yourself 240000
3. Withdraw 15000 from your Crew bank

**Expected behavior**
A warning to tell you your withdrawal will be over the maximum balance allowed.

**Software (please complete the following information):**
 - Server: Paper 1.12.2
 - Plugin version  2.15.1

**Comment by RoinujNosde** [comment]
https://github.com/RoinujNosde/SimpleClans/issues/123#issuecomment-779436333

Did you report this to Vault and/or Essentials?

**Comment by TomLewis** [comment]
I knew I already reported it somewhere, I couldn't find it! 
I made a new ticket as the same bug appeared again yesterday with a user.

I didn't report either, my guess is both projects won't fix this, but I will try to explain the best I can.

Edit: Vault is 1.13 ONLY now.

**Comment by RoinujNosde** [comment]
> I didn't report either, my guess is both projects won't fix this, but I will try to explain the best I can.

Try reporting it.
Essentials' devs are probably scared of breaking other plugins if they throw the exception they should. Well, it's better for the player to see some command error (until Vault also accommodates the new exception) than to lose their money without any explanation.

> Edit: Vault is 1.13 ONLY now.

You mean api-version: 1.13?
This won't stop it from running in older versions.
And your server version is not relevant to this issue.

**Comment by TomLewis** [comment]
That Essentials form is utterly ridiculous to fill out, it's insane the number of fields and configs you need to attach, I had to spend like 45 mins cleaning up my logs to hide sensitive information. They definitely do not need my latest.log public. But its required which is very bad practice for security.

https://github.com/EssentialsX/Essentials/issues/4110

Can you please reply to this with a technical reasoning to why it needs to be fixed, I don't think my description is good enough!

**Comment by RoinujNosde** [comment]
Closing this as Essentials confirmed the bug.

**Comment by TomLewis** [comment]
Awesome, lets hope for a fix soon!
