### ISSUE TITLE
[BUG] Palavras sem espaço no bolletin board

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/SimpleClans#172]
**Describe the bug**
Avisos no bb do clã as vezes não possui espaço

**To Reproduce**
Adicionar ou remover membro como confiável

**Expected behavior**

Mensagem com espaçamento antes do nome do líder que deu confiável.

![image](https://user-images.githubusercontent.com/51332006/115182154-dd73b200-a0af-11eb-88c6-761c150463c8.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/51332006/115137222-287fbd80-9ffb-11eb-841a-e22d4591a900.png)

![image](https://user-images.githubusercontent.com/51332006/115137183-f4a49800-9ffa-11eb-9523-4244f3578bce.png)

![image](https://user-images.githubusercontent.com/51332006/115182220-fda37100-a0af-11eb-91d7-18dd33fb130f.png)

**Additional context**

~~Mensagens muito grandes não parece ser o problema:~~

![image](https://user-images.githubusercontent.com/51332006/115137195-0a19c200-9ffb-11eb-87f0-4747149462f4.png)

![image](https://user-images.githubusercontent.com/51332006/115182373-4529fd00-a0b0-11eb-8c38-720cddc402d8.png)

**Comment by SrBedrock** [comment]
Outro problema encontrado é ao passar o mouse na mensagem:

![image](https://user-images.githubusercontent.com/51332006/115179086-eca33180-a0a8-11eb-8579-d7d4c5173721.png)

![image](https://user-images.githubusercontent.com/51332006/115179089-ee6cf500-a0a8-11eb-83ef-0e899f403f94.png)

**Comment by RoinujNosde** [comment]
Confirme se a última build corrige o bug.

Sobre o hover, me envie o seu arquivo de mensagens.

**Comment by SrBedrock** [comment]
> Sobre o hover, me envie o seu arquivo de mensagens.

Vou mandar pelo discord.

**Comment by SrBedrock** [comment]
![image](https://user-images.githubusercontent.com/51332006/116343267-7f835080-a7ba-11eb-882b-a04ef76576e4.png)
Acredito que seja resolvido adicionando espaço antes de minutos, segundos, horas e atrás.

[Edição] Verificado no arquivo de mensagens já possui o espaçamento correto:
```properties
bb.ago= atrás 
bb.moments=momentos
bb.seconds= segundos
bb.minutes= minutos
bb.one.minute=1 minuto
bb.hours= horas
bb.one.hour=1 hora
bb.days= dias
bb.one.day=1 dia
```

**Comment by RoinujNosde** [comment]
Os espaços no começo são removidos automaticamente.
Isso deve resolver:
`bb.seconds=\ segundos`
`bb.minutes=\ minutos`

**Comment by SrBedrock** [comment]
> Confirme se a última build corrige o bug.

Ultima [versão 122](https://ci.codemc.io/job/RoinujNosde/job/SimpleClans/job/Dev/122/) deu um erro ao inicializar e não carregou os dados dos clãs.

Erro: https://gist.github.com/SrBedrock/038d2be7e8d024988b5382724178ab78

**Comment by RoinujNosde** [comment]
A 123 deve resolver esse erro.

**Comment by SrBedrock** [comment]
> Os espaços no começo são removidos automaticamente.
> Isso deve resolver:
> `bb.seconds=\ segundos`
> `bb.minutes=\ minutos`

Resolvido!
![image](https://user-images.githubusercontent.com/51332006/116500221-778fe300-a884-11eb-8f85-60e48def91d4.png)
