### ISSUE TITLE
Toggled Clan/Ally chat bypasses BanManager Mutes

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#173]
**Describe the bug**
When a player is muted via BanManger, a player can toggle their Clan/ally chat to talk without needing a command and they will bypass the mute and still be able to talk into their Clan/Ally chats

**To Reproduce**
1. Get muted via BanManager
2. Toggle Crew chat to not need a command to stay in that channel
3. Talk normally to your crew/ally without being muted

**Expected behavior**
To mute the player when they try and talk in Clan/Ally chat if they are muted.

**Software (please complete the following information):**
 - Server: Paper 1.12.2
 - Plugin version 2.15.1

**Comment by RoinujNosde** [comment]
Check with BanManager's devs if they can cancel the AsyncPlayerChatEvent at LOWEST priority *as well*.

**Comment by TomLewis** [comment]
Update for anyone having the same issue, Setting `chatPriority: lowest` in BanManager and rebooting the server resolved it.
