### ISSUE TITLE
WorldGuard hook broken

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#217]
**Describe the bug**
There is a SimpleClans error on startup about WorldGuard hooks, I'm using paper 1.12.2 so having to use an older version of WG, 6.2.2, I assume the hooks are for later versions only.
https://gist.github.com/TomLewis/1e871d2c3520cbd614968dff9f7855fc

**Expected behaviour**
To hook.

**Software (please complete the following information):**
 - Server: Paper 1.12.2
 - WorldGuad: 6.2.2
 - Plugin version: 2.15.1

**Comment by RoinujNosde** [comment]
- Update SimpleClans
- Add WorldGuard6Provider to the config
- Remove WorldGuardProvider
