### ISSUE TITLE
some times on console error spamming [1.17]

### ISSUE THREAD

**Issue by comonier** [RoinujNosde/SimpleClans#219]
➜  [Error](https://hastebin.com/fuyabukahi.properties)

This server is running CraftBukkit version 3145-Spigot-9472b09-f992ce6 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

[SimpleClans] Loading SimpleClans v2.15.2

**Comment by comonier** [comment]
[https://hastebin.com/fuyabukahi.properties](url)

**Comment by RoinujNosde** [comment]
Update GriefPrevention or remove GriefPreventionProvider from the config

**Comment by comonier** [comment]
> Update GriefPrevention or remove GriefPreventionProvider from the config

config from simpleclans or griefprevention ? that is an config option ?

**Comment by RoinujNosde** [comment]
From SimpleClans

**Comment by comonier** [comment]
> From SimpleClans

➜  [Were?](https://hastebin.com/jaxahenagi.yaml)

Cant find Grief words on config.

**Comment by comonier** [comment]
Anyway updtaing GP to 16.17.1 version will fix it ?

**Comment by RoinujNosde** [comment]
It will

**Comment by comonier** [comment]
Ok give me a time before close issue to i test it pls so i will close with comment saying if it works, now there is players on my server i cant restart to upgrade griefprevention yet. but ty.

**Comment by RoinujNosde** [comment]
No problem.

**Comment by comonier** [comment]
It's fixed after update GP plugin TY <3
