### ISSUE TITLE
Trocar o comando bb para avisos

### ISSUE THREAD

**Issue by thiagogebrimm** [RoinujNosde/SimpleClans#221]
**Is your feature request related to a problem? Please describe.**
O quadrado de avisos se adicionar na versão português /clan avisos em vez de /clan bb faria mais sentido.

**Describe the solution you'd like**
Trocar no arquvio pt-BR o bb para avisos

**Describe alternatives you've considered**
..

**Additional context**

**Comment by RoinujNosde** [comment]
:+1:
