### ISSUE TITLE
How disable command translate

### ISSUE THREAD

**Issue by Finelolik** [RoinujNosde/SimpleClans#231]
![image](https://user-images.githubusercontent.com/49118663/124445627-62559a00-dd88-11eb-9b9e-5c672deb7a9a.png)
I need to return only commands in English.

**Comment by Tomut0** [comment]
Привет, ты можешь отредактировать сообщения сам. 
[Ссылка на гайд](https://simpleclans.gitbook.io/simpleclans/v/russian/how-to-setup/translation)

**Comment by Finelolik** [comment]
> Привет, ты можешь отредактировать сообщения сам.
> [Ссылка на гайд](https://simpleclans.gitbook.io/simpleclans/v/russian/how-to-setup/translation)

А в конфиге это можно отключить?

**Comment by Tomut0** [comment]
Отключить возможность менять язык?
Поставь `user-language-selector` на `false`.

**Comment by Finelolik** [comment]
> Отключить возможность менять язык?
> Поставь `user-language-selector` на `false`.

Нет. Убрать русский язык из команд.

**Comment by Tomut0** [comment]
> 
> 
> > Отключить возможность менять язык?
> > Поставь `user-language-selector` на `false`.
> 
> Нет. Убрать русский язык из команд.

Плагин переводится на [Crowdin](https://crowdin.com/project/simpleclans), поэтому если хочешь что-то изменить в русской локализации – нужно это делать самому, локально. (Ну, или предложить свой вариант на Crowdin)

Я сам недавно заметил, что русский язык в командах смотрится убого, поэтому перевёл большинство команд обратно на английский вариант.

Ты можешь скачать последнюю dev версию, в ней должен быть исправлен этот момент: [ссылка](https://ci.codemc.io/job/RoinujNosde/job/SimpleClans/job/Dev/157/artifact/target/SimpleClans.jar)

**Comment by Finelolik** [comment]
> > > Отключить возможность менять язык?
> > > Поставь `user-language-selector` на `false`.
> > 
> > 
> > Нет. Убрать русский язык из команд.
> 
> Плагин переводится на [Crowdin](https://crowdin.com/project/simpleclans), поэтому если хочешь что-то изменить в русской локализации – нужно это делать самому, локально. (Ну, или предложить свой вариант на Crowdin)
> 
> Я сам недавно заметил, что русский язык в командах смотрится убого, поэтому перевёл большинство команд обратно на английский вариант.
> 
> Ты можешь скачать последнюю dev версию, в ней должен быть исправлен этот момент: [ссылка](https://ci.codemc.io/job/RoinujNosde/job/SimpleClans/job/Dev/157/artifact/target/SimpleClans.jar)

Хорошо, попробую
