### ISSUE TITLE
2.15.3 lots of errors and stops the server booting. (broken GriefPrevention?)

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#237]
**Describe the bug**
I updated from 2.15.2 to 2.15.3 today and it prevented the server booting, but had a lot of error messages!

https://gist.github.com/TomLewis/46f31be0f89736f55883e51e2cf3208d

**Software (please complete the following information):**
 - Server: Paper 1.12.2
 - Plugin version 2.15.3

**Comment by TomLewis** [comment]
I backdated to 2.15.2, still spamming console. So I must have been on 2.15.1, makes sense as 2.15.2 you updated dependencies, so anyone on 1.12.2 is forced to use an older version of grief prevention as they don't support older versions.

**Comment by RoinujNosde** [comment]
That shouldn't prevent the server from booting, it's just spam.

Todo: suppress that error by checking if the UUID method exists.

**Comment by TomLewis** [comment]
On 2.15.3 it prevented it booting, on 2.15.2 it made the server reboot over and over, because of my wrapper, it checks for constant errors in the console and if it *thinks* there is an issue it'll auto reboot.

I backdated to 2.15.1 for now and we're all back up and running.

No idea why 2.15.3 prevented the server from finishing its boot, it's like it got stuck at that error at boot, no idea.

Edit: there are 2 errors with the Griefprevention block break is part of it too.

**Comment by RoinujNosde** [comment]
The latest [build](https://ci.codemc.io/job/RoinujNosde/job/SimpleClans/job/Dev/164/) should fix this.
