### ISSUE TITLE
Chat tags

### ISSUE THREAD

**Issue by kphoenix137** [RoinujNosde/SimpleClans#267]
**Is your feature request related to a problem? Please describe.**
Currently, the clan tag is placed before the entire name tag. Before creating a clan, my tag appears as <kphoenix_>. When creating a clan, now my tag is <Staff.<kphoenix_>. I want the middle < to be removed, however if I do that to achieve <Staff.kphoenix_>, then if I leave the clan, my name tag becomes kphoenix_>.

**Describe the solution you'd like**
I'd like the clan tag to be treated as a prefix and occupy the prefix slot with custom chat tags.

**Comment by RoinujNosde** [comment]
Use {clan} in your chat plugin's format to position the tag. 
If it doesn't work,  you can use `%simpleclans_clan_color_tag%` (requires PAPI).

**Comment by kphoenix137** [comment]
Thanks for the quick reply! I was trying {CLAN} before making this and it didn't work, but {clan} did! Thanks for the help
