### ISSUE TITLE
Name Tag colors

### ISSUE THREAD

**Issue by LightningTY** [RoinujNosde/SimpleClans#270]
I need help with the coloring of the tags for leaders and members, I don't know how this system of number for colors works

**Comment by SrBedrock** [comment]
Give an example of what you are trying to achieve

**Comment by RoinujNosde** [comment]
![images.jpeg.jpg](https://user-images.githubusercontent.com/6441328/142720482-84fcf141-5f64-4e1e-9a18-a5d5de876352.jpg)
