### ISSUE TITLE
Two new events

### ISSUE THREAD

**Issue by PikaMug** [RoinujNosde/SimpleClans#271]
**Is your feature request related to a problem? Please describe.**
Unable to support via [Unite](https://github.com/PikaMug/Unite) (and thus https://github.com/PikaMug/Quests/issues/1615).

**Describe the solution you'd like**
Addition of the following events:
- PreDisbandClanEvent (in a similar vein to #87)
- ~~PlayerResignEvent (or whatever action implies voluntarily leaving clan)~~

Both should provide access to the player/clanplayer triggering the event.

**Comment by Tomut0** [comment]
Hi, `PlayerResignEvent` is [this](https://github.com/RoinujNosde/SimpleClans/blob/master/src/main/java/net/sacredlabyrinth/phaed/simpleclans/events/PlayerKickedClanEvent.java) one.
Let's wait @RoinujNosde for his meaning about *PreDisbandClanEvent*.

**Comment by PikaMug** [comment]
@Tomut0 Are you certain? That event name implies the player being forcibly kicked from the clan; not leaving voluntarily.

**Comment by Tomut0** [comment]
> @Tomut0 Are you certain? That event name implies the player being forcibly kicked from the clan; not leaving voluntarily.

Yep, I'm sure.
`PlayerKickedClanEvent` is calling in [Clan#removePlayerFromClan](https://github.com/RoinujNosde/SimpleClans/blob/master/src/main/java/net/sacredlabyrinth/phaed/simpleclans/Clan.java#L1151) and then it uses everywhere.
That is probably a good suggestion to rename it.

**Comment by RoinujNosde** [comment]
Do you need both events to be Cancellable?

**Comment by PikaMug** [comment]
@Tomut0 Thanks. In that case, either renaming the event to PlayerLeftClanEvent or attaching a reason (RESIGNED, KICKED, BANNED, et al.) would be great.

@RoinujNosde I don't need either to be, but it would probably be best for PreDisbandClanEvent to be cancellable for consistency.

**Comment by RoinujNosde** [comment]
You mentioned you were unable to add support via Unite. Why is that?

**Comment by PikaMug** [comment]
The remaining reason is I'm unable to determine which player initiated the DisbandClanEvent.

**Comment by RoinujNosde** [comment]
Is it essential to know the initiator? 
When there are more than 1 leader, they all need to accept it in order to disband, so if you want to know this to send a message to players, you could make it generic like "The leaders decided to disband the clan".

**Comment by PikaMug** [comment]
Unite is currently only able to provide for a single leader, so yes. A separate getter would be preferable, but a list of leaders which retains order, meaning list.get(0) would return the initiator, would also be fine. LinkedList is good for this.
