### ISSUE TITLE
Loading class `com.mysql.jdbc.Driver'. This is deprecated. 

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#273]
**Describe the bug**
Im in the process of updating 1.12.2 to 1.17.1 and im reading every single error messasge as I go, this is displayed when simpleclans loads MySQL, im using MariaDB.

```[18:05:24] [Server thread/ERROR]: (com.mysql.jdbc.Driver:43) Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.```

**To Reproduce**
1. Run simpleclans on 1.17.1 PurPur with MariaDB

**Software (please complete the following information):**
 - Server: PurPur 1.17.1
 - Plugin version 2.16.0

**Comment by TomLewis** [comment]
Also has this error with GriefPrevention:
```[Server thread/WARN]: [SimpleClans] Loaded class me.ryanhamshire.GriefPrevention.Claim from GriefPrevention v16.17.1-2b69191 which is not a depend, softdepend or loadbefore of this plugin.```

**Comment by Tomut0** [comment]
These are not actually the errors. You could ignore it.
Database thing is planned to be updated, don't worry. 😄
