### ISSUE TITLE
/help shows error for a few clan commands

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#275]
**Describe the bug**
When using /help a few Crew commands are displayed wrong, I am using a custom `messages_en.properties` to change the word "Clan" for "crew" in every instance in every single message.
I would MUCH appropriate where you have the `commands.clan: crew` setting to change the command name, a variable to set separate that I can dynamically change all the mentions of the word "Clan" to crew in the messages_en.properties without having to manually update it every single time the plugin updates it!

**To Reproduce**
1. Run the command '/help

**Expected behavior**

**Screenshots**
![Oqzt4eG](https://user-images.githubusercontent.com/144046/147284457-e28bfb1f-83a3-4a57-bf82-42600c3a95f8.png)

**Software (please complete the following information):**
 - Server: PurPur 1.17.1
 - Plugin version 2.16.0

**Comment by RoinujNosde** [comment]
The bug description doesn't match the screenshot.

**Comment by RoinujNosde** [comment]
aikar/commands#358
