### ISSUE TITLE
Erro ao debandar e criar um clã com mesma TAG

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/SimpleClans#277]
**Describe the bug**
Ao debandar um clã e criar um novo clã com mesma tag, os membros do clã antigos continuam no clã novo com mesma TAG.

**To Reproduce**
1. Crie um clã com a TAG ARM e convide vários jogadores.
2. Debande o clã ARM.
3. Crie novamente o clã com TAG ARM.
4. Verifique os membros do clã, os jogadores do clã antigo estarão no clã novo.

**Expected behavior**
Ao debandar um clã e criar um clã com mesma TAG, os membros do clã debandado não deveriam estar no clã novo.

**Screenshots**
Lista de membros do clã ARM novo, após ser debandado: (utilizou apenas a mesma TAG, nome do clã é diferente)
![image](https://user-images.githubusercontent.com/51332006/147952555-c145ee84-e940-4079-96e8-64576c168107.png)
![image](https://user-images.githubusercontent.com/51332006/147952606-800aa90e-6734-4ef3-a22d-9e1878cd6bdd.png)
![image](https://user-images.githubusercontent.com/51332006/147952613-de53d1a4-89ac-4603-8279-47c7eb516cd7.png)

**Software (please complete the following information):**
 - Server: Paper 1.17.1
 - Plugin version 2.16.0

**Additional context**
Como pode ser observado, o clã foi criado dia **01 de janeiro de 2022** e vários membros não entram no server a dias.

Fudação:
![image](https://user-images.githubusercontent.com/51332006/147952927-7e0dacf5-7b2b-4978-9e78-d0655f4faa91.png)

Jogadores inativos a mais tempo que a própria data da fundação:
![image](https://user-images.githubusercontent.com/51332006/147952968-a7bccf00-d785-4eb9-9915-de3615d76520.png)

**Comment by RoinujNosde** [comment]
Pode testar com um clã novo?
Crie o clã "test", convide alguns players, disband e recrie.

**Comment by SrBedrock** [comment]
> Pode testar com um clã novo? Crie o clã "test", convide alguns players, disband e recrie.

Posso criar um clã com tag tst porque minha configuração aceita tag com apenas 3 letras ou números.

**Comment by SrBedrock** [comment]
1. Usei o comando `/clan criar TST Teste` para criar o clã.

2. Convidei três jogadores para o clã:
![image](https://user-images.githubusercontent.com/51332006/148137460-38d4a13b-8b40-4fe5-a2dc-b7caedf90728.png)

3. Defini os três jogadores como líderes:
![image](https://user-images.githubusercontent.com/51332006/148137647-3412447a-5d69-417d-bbf5-37815efc6d76.png)


4. Solicitei a exclusão do clã com `/clan debandar`:
![image](https://user-images.githubusercontent.com/51332006/148137525-948b8b31-fd96-44b0-b3c8-038d67743b44.png)

5. Usei o comando `/clan criar TST Teste` para criar o clã novamente:
![image](https://user-images.githubusercontent.com/51332006/148137552-58693544-e28d-4f74-a329-a2985966856e.png)

Nenhum erro ocorreu dessa vez.. 🤷🏻‍♂️

**Comment by RoinujNosde** [comment]
> Nenhum erro ocorreu dessa vez..

Como eu esperava...
Por algum motivo os dados desses 2 jogadores ficaram com a tag ARM, por isso ao criar de novo o clã eles foram adicionados novamente.
Pode ter ocorrido algum erro ao remover a tag...

A solução aqui é expulsar os 2 manualmente.
