### ISSUE TITLE
Not using UUID in MySQL database, duplicating users with differnt case sensativity! Use UUID!

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#282]
**Describe the bug**
So I had a bug where a user was "not online" when they got invited to a crew, but they WERE online, I looked at the database and they had multiple rows in the database, only difference was their username had 1 case change, this is where the user changes their username to something, then changes it back to something else and the data is still kept.

This is having massive issues with duplicated users having very obscure bugs like this.

**Expected behavior**
Save users as UUID in the database and then just have an array of their username history in that row

**Software (please complete the following information):**
 - Server: Purpur 1.18.1
 - Plugin version 2.16.0

**Comment by Tomut0** [comment]
> was "not online" when they got invited to a crew, but they WERE online

I don't think that it's possible to invite offline player, how did they do it?

**Comment by RoinujNosde** [comment]
> Plugin version 2.16.1

Check your version again. This one doesn't exist.

**Comment by TomLewis** [comment]
> > Plugin version 2.16.1
> 
> Check your version again. This one doesn't exist.

Just a typo. 2.16.0

**Comment by TomLewis** [comment]
Didn't mean to click close either.. sigh..

**Comment by RoinujNosde** [comment]
This was fixed on 2.16.0. The duplicate users are probably from an older version.
Just to make sure, try to use a command using an incorrect case: you should get a message saying the player hasn't played on this server.

**Comment by TomLewis** [comment]
Yes, the issue is that they are online and the plugin is saying they are offline, because there are 144 dupliate user usernames in the database (I checked manully)
You need to be saving users as UUID not by username as their unique ID.

Peolpe using mySQL can use:
```
SELECT
    id, name, COUNT(*)
FROM
    sc_players
GROUP BY
    name
HAVING 
    COUNT(*) > 1
```
This shows you all the duplicates, but you have to MANUALLY go through one by one and figure out which ones to remove.

What makes this 100000000x harder, is players that have changed thier username have their old data from their previous username, because its not using UUID!

**Comment by RoinujNosde** [comment]
If you check the table structure, you will notice that the UUID column is unique.
When a user changes their username, the plugin updates its row based on the UUID.

The problem with versions previous to 2.16 is that if a random name (or a player name, with incorrect case) was typed, a row in the db would be created for it.
Now the plugin checks if the player has played before, to prevent that.

You just need to delete these duplicate entries from your db.

**Comment by TomLewis** [comment]
phew ok, well thats simple enough. I didnt want to do it all only to have to do it again.
