### ISSUE TITLE
Adicionar suporte HEX no BB

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/SimpleClans#285]
**Describe the bug**
Ao usar HEX no quadro de avisos as cores são traduzidas para legacy.

**To Reproduce**
1. Use o comando para alterar a tag de um clã.
2. Use o comando para visualizar a mensagem no quadro de avisos.
3. Veja a cor da tag na mensagem.

**Expected behavior**
A cor da TAG ser em HEX

**Screenshots**
![image](https://user-images.githubusercontent.com/51332006/151637562-d971085a-f771-46ec-90fb-727fd3d7d18f.png)

**Software (please complete the following information):**
 - Server: 1.17.1
 - Plugin version: 1.16.2

**Comment by RoinujNosde** [comment]
Pode conferir como o BB fica no banco de dados?
Se a tag fica em HEX ou legacy.

**Comment by SrBedrock** [comment]
Tabela: `sc_clans` Coluna: `color_tag` = `§x§6§0§6§0§6§0§lH§x§9§d§9§d§9§d§lA§x§d§9§d§9§d§9§lX`

Tabela: `sc_clans` Coluna: `packed_bb` =
`1643396865158_§e§b§8[§bClã§8] §bTag alterada para §x§6§0§6§0§6§0§lH§x§9§d§9§d§9§d§la§x§d§9§d§9§d§9§lX§b.`
`1643396871584_§e§b§8[§bClã§8] §bTag alterada para §x§6§0§6§0§6§0§lH§x§9§d§9§d§9§d§la§x§d§9§d§9§d§9§lx§b.`
`1643397238285_§e§b§8[§bClã§8] §bTag alterada para §x§6§0§6§0§6§0§lH§x§9§d§9§d§9§d§la§x§d§9§d§9§d§9§lX§b.`
`1643397242797_§e§b§8[§bClã§8] §bTag alterada para §x§6§0§6§0§6§0§lH§x§9§d§9§d§9§d§lA§x§d§9§d§9§d§9§lX§b.`

**Comment by RoinujNosde** [comment]
Parece ser uma limitação da API de cores do Bungeecord.

**Comment by SrBedrock** [comment]
Revisitando o issue após commit https://github.com/RoinujNosde/SimpleClans/commit/263d129325888fb1303dda549986ab43ca93ed13, o mais engraçado é que no chat envia normalmente:

![image](https://user-images.githubusercontent.com/51332006/233979621-17a04268-1d6f-4a47-96e7-f8b731522d21.png)

O problema é especifico quando tenta exibir no quadro de avisos.

**Comment by RoinujNosde** [comment]
https://github.com/RoinujNosde/SimpleClans/blob/master/src/main/java/net/sacredlabyrinth/phaed/simpleclans/Clan.java#L1361-L1364
Acho que a culpa é desse trecho. (Mais especificamente o `new TextComponent(msg)`)

Se quiser testar com outros métodos dessa biblioteca: https://javadoc.io/doc/net.md-5/bungeecord-chat/latest/index.html
