### ISSUE TITLE
Clan Toggle Chat/Ally toggle chat bypassing chat priority. 

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#286]
**Describe the bug**
It seems when users use `/c join` to toggle their chat to their crew/ally chat that this bypasses all Mutes/Filters from other plugins that have lower chat priority than SimlpeClans.

**To Reproduce**
```
LOWEST - BanManager (Most powerful over all plugins)
LOW
NORMAL
HIGH - ChatControl
HIGHEST - SimpleClans
MONITOR (Basically useless)
```

I use BanManager for Mutes/Punishments and ChatControl for filtering bad words etc.

**Expected behavior**
When someone uses /c join and talks into the chat that SimpleClans respects chat priority

Currently using `/c this is a message` is being filtered and punishments upheld correctly, its only when they join the chat to toggle all their messages being sent that the priority is being completly ignored and they can swear/post links/bypass mutes.

**Software (please complete the following information):**
 - Server: Purpur 1.18.1
 - Plugin version 2.16.0

**Comment by RoinujNosde** [comment]
SimpleClans' chat listener is actually on LOW priority. So only plugins canceling on LOWEST will be able to block the clan chat.

**Comment by TomLewis** [comment]
Its hard coded? and LOWEST was the choice there?
I was going off this;
```
  listeners:
    priority: HIGHEST
```
I assumed that was the chat listener.

There's even this one, which I didn't think was related to chat.
```
war-and-protection:
  listener-priority: HIGHEST
```

Well that explains why people can swear and do whatever then in /c join, strangely its properly filtered when they use /c text, I think this is because I have /c on the list of commands to monitor in chatcontrol.

Well if `priority: HIGHEST` isn't doing chat priority, what is it doing?

and can we get a way to set the chat priority then? so I can fix this bug.

**Comment by RoinujNosde** [comment]
That listener priority is for the war and protection feature.

**Comment by TomLewis** [comment]
There are two listener prioritys in the settings. 

Can you please add a way to set the chat priority so I can fix this bug.

**Comment by TomLewis** [comment]
Thanks man
