### ISSUE TITLE
DiscordSRV require clan sethome to create channel for clan.

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#287]
Ahoy!

I have over 550 Clans on my server, so I cant enable the DiscordSRV intergration unless there is some sort of filter in-game or parameters that the crew has to reach to enable this feature for them.

Some ideas I have:

1. When the clan uses sethome it allows them to create a discord channel
2. A command in-game you have to run and pay for, the same as crew sethome, but for creating a discord channel for your crew.
3. X amount of members in a clan before you can enable discord channel (wont work for smaller crews)
4. Only Verified Clans

I think the way I would want it, is a Crew has to be verified then they run a command that costs them a small fee that we can customise, this will drastically reduce the cretion of channels for those that specifically want them. I have 269 verified crews ou of those 550, 269 is still a lot of channels, so having active crews use a command to populate would be great.

Then we need to figure out how it prunes inactive crews channels.

**Comment by Tomut0** [comment]
> unless there is some sort of filter in-game or parameters that the crew has to reach to enable this feature for them.

@TomLewis Hi, there is a config value for limiting: `discordchat.min-linked-players-to-create: 3`.
It allows you to control how many linked players are needed in clan to create channel in discord.

For more accurate filtering there is `discordchat.text.whitelist` option.
**Example:**
```yml
discordchat:
  text:
    whitelist:
    - myClan # Only myClan will be created in discord
```

> Only Verified Clans

Don't worry about it, only verified clans can have channel in discord right now.

**Comment by RoinujNosde** [comment]
There are several filters in place:
- Maximum amount of channels (config)
- Clan must be verified or permanent
- The clan must have at least X linked players (X > 0)
- Whitelisting (config)

**Comment by TomLewis** [comment]
Whitelisting won't ever bee used as this is manual process, maximum amount of channel's I assume means it just clips those crews of that were not named AAA, X linked players means small crews will be left out, our larger crews already have dedicated discords. 

Having an in game trigger if people want this is also a good thing, crews may not even want a discord channel!

**Comment by RoinujNosde** [comment]
#288 
Command added for creating a channel
Option to disable automatic creation of channels
