### ISSUE TITLE
Add support for Protection Stones and BlockLocker

### ISSUE THREAD

**Issue by TheCiROMG** [RoinujNosde/SimpleClans#289]
**Is your feature request related to a problem? Please describe.**
For a long time I was using SimpleClans with ProtectionStones and there was always a bug, the /land command to allow your clan to use the area, has an incompatible function that makes several users unable to use that area or those items

Also add BlockLocker so that there are no problems when protecting chests and others without problems, since if a user protects a chest with BlockLocker, it will stop using it for no reason, it is not known why

**Describe the solution you'd like**
Add a small compatibility so that there are no problems in the future

**Describe alternatives you've considered**
That the developers of the plugins work as a team to be able to solve this error, since those plugins mentioned above are widely used in survival servers and/or clans

LINKS:

https://www.spigotmc.org/resources/protectionstones-updated-for-1-17.61797/

https://www.spigotmc.org/resources/blocklocker.3268/

**Comment by RoinujNosde** [comment]
I would like to know more about this bug.
Give me a step by step on how to reproduce, details, etc
