### ISSUE TITLE
Build 2.16.1 unavailable

### ISSUE THREAD

**Issue by PikaMug** [RoinujNosde/SimpleClans#291]
**Describe the solution you'd like**
Please generate a 2.16.1 build on CodeMC repo (for Maven usage).

**Describe alternatives you've considered**
Saw the project's [ build | passing ] button links to https://www.travis-ci.com/RoinujNosde/SimpleClans but that 404'd

**Comment by RoinujNosde** [comment]
I forgot to bump the version in the latest release.
You can use 2.16.0 from the repo.
