### ISSUE TITLE
Bug/Request work with ChatControl Red

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#298]
**Describe the bug**
I reduced the clanchat `listener-priority: LOW` so ChatControl Red will filter the chat, the problem now is that when people talk in their clan join chat, the messages are displayed twice, in global and in the Clan chat.

This happeend when I changed the priority, as ChatControl red is higher up and is most likley taking over SimpleClans clan join messages, can you work with Chatcontrol API/Channels so that this can get resolved so messages are filterd. 

**To Reproduce**
1. Use ChatControl Red set in HIGH
2. Set `clanchat` to `listener-priority: LOW`
3. Use /clan join and write in chat, the message is sent twice, once in clan chat once in global chat.

**Expected behavior**
Messages to be sent into clan chat only, being filtered by ChatControl Red.

**Software (please complete the following information):**
 - Server: 1.18.1
 - Plugin version 2.16.2-7a8ac95

**Additional context**
#286

**Comment by RoinujNosde** [comment]
ChatControl needs to add a separate listener (different priority) for checking mutes.

Working like this:
ChatControl mute checker: low
SimpleClans chat: normal
ChatControl chat: high

**Comment by TomLewis** [comment]
Ahh is the "mute" the method used to not send text to a channel? 

@kangarko

**Comment by kangarko** [comment]
@RoinujNosde is there any other way than adding a second listener you can think of please? I can investigate whether listening to ChatEvent fires before asyncplayerchatevent and perhaps add some invisible metadata to the player to notify our event that the player chatted using simpleclans, or use your API to check if the player is joined to chat in simpleclans in our event.

**Comment by RoinujNosde** [comment]
Well, if you are willing to use SC's API, there is definitely an alternative!

```java
ClanPlayer cp = clanManager.getCreateClanPlayer(event.getPlayer().getUniqueId());
if (cp.getChannel() != Channel.NONE) {
    //the player is joined to one of SC's channels
}
```

**Comment by kangarko** [comment]
@RoinujNosde I am! Got my checker to work directly in your chatevent instead, everything seems to be working except changing the message:

You can see that the console has properly printed out that we changed the message, and then I called event#setMessage but it still did send the original version in your clan chat. SimpleClans priority is on low, ChatControls is on high so we dont even see the message before you process it. I cannot event catch that message in our AsyncPlayerChatEvent. How to proceed please?

![a](https://i.imgur.com/IqcqOFD.png)

**Comment by RoinujNosde** [comment]
It was a bug on our end, just fixed it on dev. 

Is the event getting cancelled correctly?

**Comment by kangarko** [comment]
Working now, many many thanks!

Small thing, the console claims I am running an outdated version even tho I am on your latest dev build:
![image](https://user-images.githubusercontent.com/1918426/156418841-772f1822-12e9-4711-86df-ec4f75af5471.png)

**Comment by RoinujNosde** [comment]
Thanks for letting me know!
Fixed that as well.

**Comment by kangarko** [comment]
If you'll ever need free access to my plugins to add integration on your end just let me know. Thanks and keep up the good work!

**Comment by TomLewis** [comment]
Woohoo! amazing collaboration! Thanks guys! Look forward to players not being able to do very suspect things in their crew chats!
