### ISSUE TITLE
Spigot (Bedrock) players can't accept invite

### ISSUE THREAD

**Issue by ltjessem** [RoinujNosde/SimpleClans#303]
It's not clear to players connected via Spigot how to accept a clan invite. They can't click links in chat so [ACCEPT] and [DENY] don't work. 
The easiest and quickest way to solve this would simply to add a line under these links with the text "or, type /clan accept or /clan deny"

**Comment by RoinujNosde** [comment]
You can edit the messages file and add that line.
Follow this guide: https://wiki.roinujnosde.me/simpleclans/how-to-setup/translation
