### ISSUE TITLE
/crew lookup crashes server when Mojang auth servers are unreachable 

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#306]
**Describe the bug**
my server was just crashed as an admin did a crew lookup on a user and by the looks of the error there is no try/catch for if the mojang server is down and crashes the server. Can you please check for this so it does not happen again, thank you.

https://gist.github.com/TomLewis/917dc755107ae8c8416f4ecb316a5228

**To Reproduce**
1. Any issues with Mojang servers
2. Crew lookup
3. Crashes server.

**Expected behavior**
To report backto the user a lookup can not happen right now as the mojang servers are down and not crash.

**Software (please complete the following information):**
 - Server: Purpur 1.18.1
 - Plugin version 2.16.2

**Comment by RoinujNosde** [comment]
Not an error/exception, so a try/catch wouldn't fix.
The server thread just hang for a long time while the API was unavailable. 

Was this caused after trying to lookup a player that has never played on your server?

**Comment by TomLewis** [comment]
The player has played before, but im not 100% the spelling was correct. Does it only trigger the API call if its not in the database?

**Comment by RoinujNosde** [comment]
Check the nickname spelling in your logs, please.


> Does it only trigger the API call if its not in the database?

That's what I think, but I would like to confirm before implementing a solution.
