### ISSUE TITLE
Can't choose language on PaperSpigot 1.16.4, plugin ver: 2.16.2

### ISSUE THREAD

**Issue by Xablauzero** [RoinujNosde/SimpleClans#311]
Can't choose language in the config file.

1. Go into config.yml
2. Change language to: pt-BR
3. See error

Replace the translation inside the java one, but no matter how I try to 

 - Server: PaperSpigot 1.16.4
 - Plugin version: 2.16.2

no matter what I type, BR, br, pt, pt_BR etc, I can't change the language.

**Comment by RoinujNosde** [comment]
The code is pt_BR.

You probably didn't see the language changing because your *personal* language is set to English, but new players will.

Change your personal language in the GUI.

**Comment by Xablauzero** [comment]
> 

OH, NO WAY IT ACTUALLY WORKED.

Also, que estranho agora que vi que você é brasileiro... Foda que pensei em recompilar o projeto do github e então colocar a tradução dentro e dps buildar q nem um cara lá da rússia fez, n tinha visto esse bgl de personal language, valeu pela ajuda brother.

**Comment by RoinujNosde** [comment]
De nada :)
