### ISSUE TITLE
Como tiro estas coisas??

### ISSUE THREAD

**Issue by Climbby** [RoinujNosde/SimpleClans#320]
![2022-06-23_14 20 59](https://user-images.githubusercontent.com/107854416/175308994-90501ae2-f6ae-4447-ab9a-bb1258c7329f.png)

Eu queria mudar os Parênteses amarelos, tirar a linha "status", tirar a linha "taxa", tirar a linha "fundado" e tirar a linha e desativar a funcionalidade "inativo"

**Comment by RoinujNosde** [comment]
Olá, 
A parte amarela vc modifica na config, seção "tag".

Para remover aquelas linhas, é só editar o arquivo de mensagens: abra o .jar, copie messages_pt_BR para a pasta do plugin e edite o arquivo lá.

A funcionalidade inativo pode ser desativada definindo inactive-days como 0.

**Comment by Climbby** [comment]
Já mudei a secção tag e não muda no /clan profile, apenas muda no chat

**Comment by RoinujNosde** [comment]
Erro meu.
Aquela cor também deve ser modificada no arquivo de mensagens.
