### ISSUE TITLE
Clans doesnt sync on multiple servers when connected to SQL

### ISSUE THREAD

**Issue by typicalsmc** [RoinujNosde/SimpleClans#325]
**Describe the bug**
clans doesnt sync on multiple servers when connected to SQL

**To Reproduce**
1. install plugin on sql storage
2. parse placeholder and do /clan

**Expected behavior**
clans synced

**Software (please complete the following information):**
 - Server: This server is running Pufferfish version git-Pufferfish-72 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 8f05a00 on HEAD)
 - Plugin version SimpleClans version 2.16.2-51f82ba

**Comment by Tomut0** [comment]
Enable `use-bungeecord` at both plugin configs and set connection to one MySQL database.

This will sync clan creation and some other things.

Bungecoord isn't fully supported yet.

**Comment by typicalsmc** [comment]
ok, will there be redis support in the future ?

**Comment by Tomut0** [comment]
> ok, will there be redis support in the future ?

We have seen someone made it before, but didn't send a pull request. This is disappointing. 

Redis would be a cool feature, but I guess we're focusing on multiplatforming currently.

**Comment by typicalsmc** [comment]
cross server is cool too

**Comment by typicalsmc** [comment]
> > ok, will there be redis support in the future ?
> 
> We have seen someone made it before, but didn't send a pull request. This is disappointing. 
> 
> Redis would be a cool feature, but I guess we're focusing on multiplatforming currently.
> 
> 

is the code for redis public on their fork ?

**Comment by Tomut0** [comment]
@TypicalShavonne No, it's not public.

**Comment by RoinujNosde** [comment]
Duplicate of #209
