### ISSUE TITLE
Opção para bloquear código de cores no chat de clãs

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/SimpleClans#337]
**Is your feature request related to a problem? Please describe.**
Jogadores usam códigos de formatação como `&k` para floodar o chat de clãs e aliados.

**Describe the solution you'd like**
Adicionar uma configuração para bloquear o uso no chat do clã e aliado como já existe para a TAG.

Exemplo:
```yml
  disallowed-chat-colors:
  - k
  - m
  - n
  - o
```

**Comment by RoinujNosde** [comment]
Acho que nesse caso é melhor permissão pra usar cores.

**Comment by SrBedrock** [comment]
> Acho que nesse caso é melhor permissão pra usar cores.

Permissão pelo sistema de clãs?

**Comment by RoinujNosde** [comment]
Pelo plugin de permissões.

**Comment by SrBedrock** [comment]
> Pelo plugin de permissões.

Como posso fazer isso?

**Comment by RoinujNosde** [comment]
Vou adicionar uma permissão tipo simpleclans.member.chatcolor

**Comment by SrBedrock** [comment]
Seria interessante dividir a permissão entre uso de cores e códigos de formatação.

**Comment by RoinujNosde** [comment]
simpleclans.member.chatcolor.\<cor ou formato>
