### ISSUE TITLE
Maven repository misconfigured

### ISSUE THREAD

**Issue by PikaMug** [RoinujNosde/SimpleClans#352]
While working on a Maven project to support both SimpleClans and [Development-Party-And-Friends-For-Spigot](https://github.com/Simonsator/Development-Party-And-Friends-For-Spigot), the order in which the SimpleClans repository is placed has a problematic effect.

```xml
<repository>
    <!-- SimpleClans -->
    <id>roinujnosde-repo</id>
    <url>https://repo.roinujnosde.me/#/releases/</url>
</repository>
<repository>
    <!-- Party and Friends -->
    <id>simonsators-repo</id>
    <url>https://simonsator.de/repo</url>
</repository>
```

Credit to @Simonsator for realizing that, because Maven searches repositories from top-to-bottom, when it goes to retrieve Party and Friends (or any dependency I imagine), your Maven server returns success code 200 even though it doesn't have that jar; it should be returning 404 instead.

The workaround in my case was to place your repository at the bottom / below simonsators-repo, so Maven would find it there first, but this isn't obvious to many. Please address this misconfiguration for anyone else looking to depend on SimpleClans.

**Comment by RoinujNosde** [comment]
The actual problem is that `#` in the repo URL.
Change it to `https://repo.roinujnosde.me/releases/`

**Comment by PikaMug** [comment]
That would be entirely my fault. Thanks!

**Comment by RoinujNosde** [comment]
No problem. You're welcome.
