### ISSUE TITLE
Use different permission for `auto-group-groupname`

### ISSUE THREAD

**Issue by NyaomiDEV** [RoinujNosde/SimpleClans#357]
I won't spend that much time compiling the entire form.

Since giving `group.<TAGNAME>` permission is problematic under LuckPerms, just use another permission prefix. Either make the user define it (for example `clan` for `clan.<TAGNAME>` or `whatever.nested.node` for `whatever.nested.node.<TAGNAME>`) or just switch it to a known not problematic one, for example `simpleclans.clan.<TAGNAME>` which falls under the plugin's permission namespace.

**Comment by RoinujNosde** [comment]
`group.` is used to allow server owners to integrate clans with LuckPerms.

**Comment by Tomut0** [comment]
I think you misunderstood how this config option works.

You have to create `sc_leader` (or `sc_trusted`, `sc_untrusted`, `clan_<tag>`) group in LuckPerms and there all leaders (or trusted, untrusted, clan's) players would be affected with your defined permissions.

**Comment by SrBedrock** [comment]
I believe this system can be improved by creating context using the [LuckPerms API](https://luckperms.net/wiki/Developer-API-Usage#the-basics-of-context)
How the context system works: https://luckperms.net/wiki/Context

**Comment by SrBedrock** [comment]
Added permission `group.<clan-tag>` is something very problematic because luckperms saves group information via permission `group.<rank-name>`, this can easily create problems where you need to list all group names as tags not allowed in SimpleClans configuration and etc.

**Comment by NyaomiDEV** [comment]
The quickest workaround of them all would be `group.sc_clan_<tag>`
