### ISSUE TITLE
GUI items are moveable & not working after first click

### ISSUE THREAD

**Issue by altnoidenjoyer** [RoinujNosde/SimpleClans#362]
**Describe the bug**
Whilst using the GUI, you can move the GUI items around and nothing happens when you click them the first time. It will work once you place the items back in their correct spot and click multiple times on the item.

**To Reproduce**
Click items in GUI

**Expected behavior**
The GUI items should not be moveable and it should execute the command on the first click.

**Screenshots**
I attached a video

**Software (please complete the following information):**
 - Paper 1.19.4
 - SimpleClans 2.18.1

https://user-images.githubusercontent.com/70487404/228516072-0de640ba-4663-43a9-96e2-a412b5ba844c.mp4

**Comment by Tomut0** [comment]
It's not moveable by default. 

Can you try using a lower paper version? Also is this problem can be reproduced only with SimpleClans installed on your server?

**Comment by Tomut0** [comment]
Seems to be a visual bug.
