### ISSUE TITLE
[Console Spam] My console gets spammed with this message every restart.

### ISSUE THREAD

**Issue by zrussellgaming** [RoinujNosde/SimpleClans#376]
**Describe the bug**
My console gets spammed with a few lines of messages. Telling me to report it.

**To Reproduce**
1. Restart the server.

**Expected behavior**
For the Console to not get spammed with this message.

**Screenshots**
None.

**Software (please complete the following information):**
 - Server: Paper MC 1.19.4
 - Plugin version 2.18.1

**Additional context**
PasteBin Link ---> https://pastebin.com/j5MPp2nV

**Comment by Tomut0** [comment]
https://github.com/RoinujNosde/SimpleClans/issues/373#issuecomment-1534644992
