### ISSUE TITLE
Add Messages and GUI to Plugin Folder for Customization

### ISSUE THREAD

**Issue by Shanman150** [RoinujNosde/SimpleClans#377]
While I like the messages for our commands overall, some could use tweaking on our server. Making the messages that the plugin uses available for server owners to edit would allow them to add in server-specific flair, as well as clean up the /clan help page, which can be confusing for players.

On my server in particular, we have removed all teleportation. The /clan regroup command still shows up in the GUI even though it has been disabled, which has led to questions about why it doesn't work. A different message when the command fails would help to explain this. Also, the /clan war command is very rarely used on our server, so players do not expect their plots to become vulnerable. We have tried to make this very clear in our own help files, but being able to edit the /clan war message to make the risks clear would also remove any confusion.

Regarding the GUI, my server typically uses chat commands only, but the GUI has been very helpful. However, it is not customizable on our end and we have really narrowed the scope of SimpleClans for use on our server. Again, the /clan regroup icon in particular raises questions from players. Being able to customize/remove elements of the GUI as other plugins allow would allow server admins to customize the GUI for their own implementation of SimpleClans.

**Comment by RoinujNosde** [comment]
Please refer to the [wiki](https://wiki.roinujnosde.me) on how to customize the messages.

As for GUI customization, it's not possible yet. I started developing it, but don't have time to finish.
