### ISSUE TITLE
[ERROR] [SimpleClans] Error saving modified ClanPlayers:

### ISSUE THREAD

**Issue by GetSlained** [RoinujNosde/SimpleClans#386]
On restart, clan players get kicked/moved to old clans.

27.07 16:35:01 [Server] Craft Scheduler Thread - 107/[ERROR] [SimpleClans] Error saving modified ClanPlayers:
27.07 16:35:01 [Server] [INFO] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE] A UNIQUE constraint failed (UNIQUE constraint failed: sc_players.name)

**Comment by Tomut0** [comment]
You have a duplicated row in your database. It can happen for various reasons. 
Using `/clan admin purge [playerName]` would delete the data of the player.
