### ISSUE TITLE
Clan roster massive delay

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#39]
**Describe the bug**
Multiple issues with Crew roster.

1) Clicking a crew roster with 100's of users takes AGES to populate to create its cache, its as though it creates a cache PER PLAYER instead of per crew of their heads, as each person that clicks it has to wait for AGES for it to load, it should be a cache per crew not cache the crew for each player that clicks it.
2) When clicking the Crew roster GUI, when it finally loads you can not click the next button, it just does nothing, no next page, no errors.

**To Reproduce**
1. Run `/clan` 
2. Click on Roster and wait for it to populate 
3. Click the next page button

**Expected behavior**
For it to load the next page

**Screenshots**

![Screenshot 2020-08-18 16 04 51](https://user-images.githubusercontent.com/144046/90530272-9625d200-e16c-11ea-8e29-f4c83dac8918.png)

**Software (please complete the following information):**
 - Server: paper 1.12.2
 - Plugin version 2.1.3.0

**Comment by RoinujNosde** [comment]
You mentioned massive lag on the title. You meant delay, right?

1. The cache is per server and it expires every hour.
Do the following: open the roster, let it load. Ask someone (from the same clan) to do the same, this second person shouldn't experience this delay.

2. Does the loading message show on the next button?

**Comment by TomLewis** [comment]
> 
> 
> You mentioned massive lag on the title. You meant delay, right?
> 
>     1. The cache is per server and it expires every hour.
>        Do the following: open the roster, let it load. Ask someone (from the same clan) to do the same, this second person shouldn't experience this delay.
> 
>     2. Does the loading message show on the next button?

Delay is a better word, updated.

This delay cant be just for loading 1 page of a crew? A crew with about 60 people in it took a good 60-120 seconds to load.
When one person clicks it, is it loading the entire servers crews into the cache? 
I have 1348 clans, and 13,713 people in my sc_players table.

I assume its caching heads? When one crew does their roster is it doing the entire crew, the entire server, or just that 1 page that there loading?


As for the broken next page button, its not saying loading, no. it does nothing when clicked.

**Comment by RoinujNosde** [comment]
> I assume its caching heads?

Yes

> When one crew does their roster is it doing the entire crew, the entire server, or just that 1 page that there loading?

Just one page

**Comment by RoinujNosde** [comment]
> As for the broken next page button, its not saying loading, no. it does nothing when clicked.

Got it, just found the problem.

Self-note: the Paginator is being recreated when the button is clicked.

**Comment by RoinujNosde** [comment]
@TomLewis Is your test server on the same network as the live one?

**Comment by TomLewis** [comment]
> 
> 
> @TomLewis Is your test server on the same network as the live one?

yes! its the same machine!

**Comment by RoinujNosde** [comment]
> You can request the same profile once per minute, however you can send as many unique requests as you like.

(From wiki.vg) 

Maybe you ran both servers at the same time and reached the limit?

**Comment by TomLewis** [comment]
> 
> 
> > You can request the same profile once per minute, however you can send as many unique requests as you like.
> 
> (From wiki.vg)
> 
> Maybe you ran both servers at the same time and reached the limit?

Are you not loading per page tho? Shouldn't even touch the limit, only if you are trying to load all 250,000 users, that might be an issue hahaha

**Comment by RoinujNosde** [comment]
> only if you are trying to load all 250,000 users

That's not the case haha

It shouldn't touch the limit if you are using one server on the network.
But if you use 2 at the same time and try to get the skin of the same player you will have to wait 60 seconds.

**Comment by TomLewis** [comment]
> It shouldn't touch the limit if you are using one server on the network.

The test server is barley used, it has only a few players a day on it, I saw that SimpleClans has a bungee setting would this not contradict only using it on one server, I would like to use it on multiple so I can test/use it on other servers.
You could keep a cahce in MySQL thats shared?

**Comment by RoinujNosde** [comment]
I've developed a task that gets all skins on enable and updates them every hour.
So players shouldn't experience any delay. Would you like to test it?

Maybe you could give me some feedback, like: get all skins or only from players in clans (the remaining would be loaded when need, ex. Leaderboard)

> I saw that SimpleClans has a bungee setting

This setting is misleading... I need to implement real bungee support or remove it.

**Comment by TomLewis** [comment]
> I've developed a task that gets all skins on enable and updates them every hour.
> So players shouldn't experience any delay. Would you like to test it?

Yes I can test! I don't think it a good idea pulling on server startup as that adds loading time until the server is working, but there has to be a way to do it based on how active crews are.

Maybe:
1. For speed have a placeholder head "hourglass" when loading heads, so as soon as you click it, all the users load and if they are not cached it shows a hourglass until they are loaded. https://minecraft-heads.com/custom-heads/search?searchword=hourglass
2. Pull heads asynchronous based on active crews once the servers started, So if you track how active crews are, maybe do a call for just these in async.
3. You could update individual heads once someone logs on per player, player logs on, cache their skin for 5days (let us set the time)

How is there not an library already that caches skins, it seems like there should be something that already exists!

I have 13,000 crews, but I have only about 250 that are active, so this could be done for active crews only.

**Comment by RoinujNosde** [comment]
> I don't think it a good idea pulling on server startup as that adds loading time until the server is working

It's async.

> How is there not an library already that caches skins, it seems like there should be something that already exists!

Bukkit does it. This is what SC is using.

1 and 3: I would have to create my own caching system. I rather avoid doing so as it would require a different class per supported Spigot version.

2: What makes a clan active? Not only on server start, but every hour, as the cache expires.

**Comment by TomLewis** [comment]
Alright, did you find the issue with going to the next pages? They straight up just dont work.

**Comment by RoinujNosde** [comment]
I fixed it.

**Comment by SrBedrock** [comment]
> > What is "use-threads" as mine is set to false.
> 
> This option writes changes to the db using a different thread to not cause lag on the main thread.

`[13:09:35 ERROR]: Nag author: 'Phaed' of 'SimpleClans' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.`

**Comment by RoinujNosde** [comment]
@SrBedrock `use-threads: true` gives you that warning? Open a new issue, please.

**Comment by SrBedrock** [comment]
> @SrBedrock `use-threads: true` gives you that warning? Open a new issue, please.

Yes.

**Comment by SrBedrock** [comment]
Issue open #49

**Comment by TomLewis** [comment]
After using 2.13.1 Clicking on Roster still has a massive delay even with cache-player-heads.

I still suggest placeholder heads until they are loaded into cache instead of waiting 60-120 seconds for it to finish loading.

Then It would be nice to have a setting to manage the cache, most players dont change their skin that often, I would set my cache to 1 month or something high.

**Comment by RoinujNosde** [comment]
Can you send me your playerdata folder? So that I can try to improve the caching.
(Information playerdata files contain: https://minecraft.gamepedia.com/Player.dat_format)

**Comment by TomLewis** [comment]
> 
> 
> Can you send me your playerdata folder? So that I can try to improve the caching.
> (Information playerdata files contain: https://minecraft.gamepedia.com/Player.dat_format)

I can, its very large. 1.5GB just for the playerdata folder.

**Comment by RoinujNosde** [comment]
> I can, its very large. 1.5GB just for the playerdata folder.

It's alright

**Comment by TomLewis** [comment]
> 
> 
> > I can, its very large. 1.5GB just for the playerdata folder.
> 
> It's alright

Alright, Let me download a backup of my world, then I will extract this folder, re-compress it and send it to you on Discord.

**Comment by RoinujNosde** [comment]
@TomLewis still an issue?

**Comment by TomLewis** [comment]
Did I send you the data? I cant remember now.
The clan roster is still very, very slow. I still suggest a placeholder head until they are loaded, so then the page opens instantly with the placeholder and loads their heads on top. Thats how the "Heads Database" loads custom heads.
https://www.spigotmc.org/resources/head-database.14280/

**Comment by RoinujNosde** [comment]
> Did I send you the data? I cant remember now.

Nope.

> The clan roster is still very, very slow. I still suggest a placeholder head until they are loaded, so then the page opens instantly with the placeholder and loads their heads on top. Thats how the "Heads Database" loads custom heads.
https://www.spigotmc.org/resources/head-database.14280/

I would like to test first the current solution.
