### ISSUE TITLE
/crew rivalries or /crew alliances shows all clans?

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#40]
**Describe the bug**
Both /crew rivalries or /crew alliances do not display the correct list of rivalries or alliances per clan you are in, its displaying all crews in order?

**To Reproduce**
1. Run `/clan rivalries`  or `/clan alliances`
2. All clans are listed

**Expected behavior**
For it to just load the alliances and rivalries  of the crew you are in.

**Software (please complete the following information):**
 - Server: paper 1.12.2
 - Plugin version 2.1.3.0

**Comment by RoinujNosde** [comment]
This is the intended behavior. To see only your own clan's alliances/rivalries you can use /clan profile.

**Comment by TomLewis** [comment]
Wait what? Why is this intended? Its just listing all crews? Nothing to do with alliances / rivalries at all?

If I run /crew alliances, it should open up the GUI or list in chat my crew alliances? what?

**Comment by RoinujNosde** [comment]
/clan alliances shows every clan AND their alliances.

The same with rivalries.

> If I run /crew alliances, it should open up the GUI or list in chat my crew alliances? what?

Just listing what I said above in chat.

**Comment by TomLewis** [comment]
This makes no sense

**Comment by RoinujNosde** [comment]
> 
> 
> This makes no sense

Why not? 😕 
It's a way to see who is friends (or enemy) with whom.

I would agree with you if there was no way to list your clan's allies/rivals...

**Comment by TomLewis** [comment]
When I run it, it just lists crews but nothing else, it shows no other information. People expect it to show their crews alliances or rivalries, either in the GUI or list in chat. 

you could even have /crew rivalries <tag> to list that crews rivalries.

I have 13,000 crews...

**Comment by RoinujNosde** [comment]
![image](https://user-images.githubusercontent.com/6441328/90696984-c3997b00-e253-11ea-96a0-04dd6de46f85.png)

This is what it should look like.
Can you send me a screenshot of the command output on your server?

**Comment by TomLewis** [comment]
It does not show the 2 columns, it squashes them into one, you have not tested with real world crew names, only short ones.

If you want i can send you my database of real world crews for you to test with, so you have some real working data.

![2020-08-19_23 54 00](https://user-images.githubusercontent.com/144046/90697878-4c75de00-e277-11ea-9792-fc124e02c428.png)

edit: Also chat moves so fast, its always separated with messages coming in too, might be better in a GUI?

**Comment by RoinujNosde** [comment]
> If you want i can send you my database of real world crews for you to test with, so you have some real working data.

Send it via DM on Discord.

**Comment by RoinujNosde** [comment]
> If you want i can send you my database of real world crews for you to test with, so you have some real working data.

Send it via DM on Discord.

**Comment by TomLewis** [comment]
Sent!
