### ISSUE TITLE
Add a feature to specify the names/prefixes for DB tables

### ISSUE THREAD

**Issue by vertexofvortex** [RoinujNosde/SimpleClans#403]
**Is your feature request related to a problem? Please describe.**
I want to store all the SimpleClans data in the database and it's possible, however, if I have multiple servers with separate clans, I have to create an additional DB for each server. That isn't good, because I cannot properly setup relations between tables in different databases to integrate them with my fancy API for the website.

**Describe the solution you'd like**
Make possible to specify the name for each database table or at least prefix for all database tables.

**Describe alternatives you've considered**
Mentioned above.

**Comment by RoinujNosde** [comment]
Hello,
Can you give this [build](https://github.com/RoinujNosde/SimpleClans/actions/runs/6645242517) a try?
Remember to backup your data.
