### ISSUE TITLE
Bedrock users can't be invited.

### ISSUE THREAD

**Issue by OreCraftNetwork** [RoinujNosde/SimpleClans#406]
**Describe the bug**
Bedrock users with GeyserMC and Floodgate cannot be invited to clans with the prefix "."

**To Reproduce**
1. Run the command '/clan invite with "."'
2. Example '/clain invite .example'
3. Error: .example is not a valid user.

**Expected behavior**
I expected the plugin to treat the player with that prefix like any other, it doesn't make much sense for this to happen and it can't be changed at our own risk.

**Screenshots**
![image](https://github.com/RoinujNosde/SimpleClans/assets/93739264/84b13a48-089d-480d-976f-db03d29e3939)

**Software (please complete the following information):**
 - Server: [Paper 1.17.1]
 - Plugin version [latest]

**Comment by Tomut0** [comment]
Checkout your `config.yml`.

```yaml
settings:
    username-regex: '(\.|\*){0,1}[a-zA-Z0-9_$]{1,16}'
```
Should let you invite bedrock users.

**Comment by OreCraftNetwork** [comment]
![image](https://github.com/RoinujNosde/SimpleClans/assets/93739264/e6942406-8980-4797-a675-a0cda937a65b)

This is my current setup. Do you mean that if I put the one you sent me it would work?

**Comment by Tomut0** [comment]
> ![image](https://user-images.githubusercontent.com/93739264/274157993-e6942406-8980-4797-a675-a0cda937a65b.png)
> 
> This is my current setup. Do you mean that if I put the one you sent me it would work?

I think so. Try it.

**Comment by OreCraftNetwork** [comment]
> > ![image](https://user-images.githubusercontent.com/93739264/274157993-e6942406-8980-4797-a675-a0cda937a65b.png)
> > This is my current setup. Do you mean that if I put the one you sent me it would work?
> 
> I think so. Try it.

Yes, work now. Thanks

**Comment by comonier** [comment]
what config ? from simpleclans or other plugin? i try it and not works

**Comment by RoinujNosde** [comment]
> what config ? from simpleclans or other plugin? i try it and not works

@comonier what error message did you get?
