### ISSUE TITLE
Allies/Rivals hover over goes off the screen

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#41]
**Describe the bug**
When you hover over a crew with a lot of allies/rivals the text goes off the screen

**Expected behavior**
There to be a limit to clans listed per line that we can set in the config, say 5-10 or something.

**Screenshots**
https://i.imgur.com/iJWMCLa.png

**Software (please complete the following information):**
 - Server: Paper 1.12.2
 - Plugin version 2.1.3.0

**Comment by RoinujNosde** [comment]
Duplicate of #36
