### ISSUE TITLE
Config file reset every time the server crash on 1.20.4 papermc

### ISSUE THREAD

**Issue by Meekness1** [RoinujNosde/SimpleClans#412]
**Describe the bug**
Config file reset every time the server crash on 1.20.4 papermc

**To Reproduce**
1. Start server
2. Wait for crash
3. Config reset

**Expected behavior**

**Comment by Tomut0** [comment]
> Config file reset every time the **server crash**

When a server crashes, it's not normal behaviour. Try to eliminate the cause of the crash and everything will be fine. 👍
