### ISSUE TITLE
[Bug] Discord chat won't work after reboots

### ISSUE THREAD

**Issue by triesharder** [RoinujNosde/SimpleClans#417]
**Describe the bug**
The discord bridge will only function after running `/clan discord create`. This can be confusing for the players

**To Reproduce**
1. Have a discord channel for your clan.
2. You can see that messages will be delivered normally
3. Reboot the server
4. Not anymore, fixable via `/clan discord create`

**Expected behavior**
**if `discordchat.auto-creation = true`**
When an players uses it's clan chat, the plugin should confirm the existence of an correspondent channel on discord and make the bridge

**Software (please complete the following information):**
 - Server: purpur-1.20.1-2062
 - Plugin version: Compiled from [ad910e9](https://github.com/RoinujNosde/SimpleClans/commit/ad910e9c309e83dfbaa508d1c86f45e982ec4ab1) with `mvn clean package install`

**Comment by Tomut0** [comment]
> The discord bridge will only function after running `/clan discord create`.

When a player creates a clan, `discordchat.auto-creation = true` should create a discord channel.
If not, the clan doesn't meet the requirements.

You can enable `settings.show-debug-info` to figure out what happens.

**Comment by Nishikiyama** [comment]
bump

Did you fix the issue or still need help?

**Comment by triesharder** [comment]
had no updates, i just forgot to upload debug-info here
