### ISSUE TITLE
Custom Messages.yml stopped working between 2.1.2.1 & 2.13.0

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#42]
**Describe the bug**
This is driving me insane, I have a test server, on the same physical server, same serer software (paper 1.12.2) but slightly different simpleclans versions, 2.1.2.1 on test server and 2.13.0 on live server.

When I updated today my live server with 2.13.0 its not picking up all my custom changes to my messages.properties after a reload or a /crew reload. its got some of my custom messages but not all of them, but it works perfectly fine on my test server.

Here's my messages.properties
https://gist.github.com/FrozenBeard/5321a7f99f8204c519372fc47a227c1e

For example im trying to get my GUI changes live, these are fine on my test server, but not on 2.13.0.

**Software (please complete the following information):**
 - Server: Paper 1.12.2
 - Plugin version 2.1.2.1 & 2.13.0

**Comment by RoinujNosde** [comment]
Rename your messages file to match what you set on language. Ex.: 

language: en

messages_en.properties

**Comment by TomLewis** [comment]
> 
> 
> Rename your messages file to match what you set on language. Ex.:
> 
> language: en
> 
> messages_en.properties

Top man! fixed! The plugin auto created messages.properties mind when I upgraded as it was upgrading it from language.yml, so it automatically needs to do this for other people.
