### ISSUE TITLE
Cant delete ranks with spaced in them.

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#48]
**Describe the bug**
Either using the command or GUI, after you have created a rank with a space in its name, you can not delete or assign it.

**To Reproduce**
1. `/clan rank create` - in chat type a rank name with a space `My rank`
2. `/clan`, click your Clan
3. Click helmet
4. Right click to delete `My Rank`, it will fail saying `usage /crew rank delete [rank]`

**Expected behavior**
Either do not allow spaced in Rank names, or give each rank its own Unique ID to delete.

**Software (please complete the following information):**
 - Server: Paper 1.12.2
 - Plugin version 2.13.0

**Comment by RoinujNosde** [comment]
Thanks.
New ranks will have spaces replaced with underlines.
And players will be able to delete the invalid ones.

**Comment by TomLewis** [comment]
Was this added into 2.14.0?

**Comment by RoinujNosde** [comment]
Yep.
Forgot to mention it.
