### ISSUE TITLE
Add some basic permissions when none defined

### ISSUE THREAD

**Issue by Freddo3000** [RoinujNosde/SimpleClans#53]
**Is your feature request related to a problem? Please describe.**
Right now unless I've missed something SimpleClans is dependent on permissions being set through some permission handler, such as Luckperms, instead of having some basic ones defined.

Right now non-op users cannot even use basic commands such as `/clan` with no parameters.

**Describe the solution you'd like**
`simpleclans.leader.*`, `simpleclans.member.*` and `simpleclans.anyone.*` should be available to users by default unless otherwise stated. This would allow the plugin to be a bit more plug-n-play, for those who don't want to do permissions configuration.

**Describe alternatives you've considered**
Perhaps have a config option for it.

**Additional context**
<details>
<summary>Plugins list</summary>

* **Simpleclans 2.12.1**
* **Dynmap-SimpleClans 1.4.0**
* BetterSleeping
* BigDoors
* BKCommonLib
* Brewery
* Cannons
* Chairs
* DiscordSRV
* Dynmap
* ImmersiveCampfires
* LockettePro
* LogBlock
* PwnPlantGrowth
* ShipsBukkit
* Shopkeepers
* TrainCarts
* WorldBorder
* worldedit

</details>

**Comment by RoinujNosde** [comment]
That makes sense.
Until implemented, you can edit the plugin.yml file and change the permissions from default: false to default: true.
