### ISSUE TITLE
Adicionar comando para bloquear recebimento de convites

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/SimpleClans#57]
**Is your feature request related to a problem? Please describe.**

Muitos jogadores não querem fazer parte de um clã, líderes de clãs enviam convites de clã para jogadores sem antes perguntar se o jogador quer ou não participar do clã.

**Describe the solution you'd like**

Seria interessante adicionar um comando para bloquear o recebimento de convistes de clãs.

**Describe alternatives you've considered**

Adicionar comando para alternar o recebimento de convites de clã.
Comando: `/clan toggle invite`
Descrição: Ativar ou desativar o recebimento de convites de clãs.
Permissão: `simpleclans.anyone.invite-toggle`

Ao enviar um convite para o jogador que estiver com convites desativados, receber uma mensagem avisando que o jogador não está recebendo convites de clã.

**Comment by RoinujNosde** [comment]
Armazenar decisão do usuário em uma flag.
