### ISSUE TITLE
Deny &k, &l, &m, &o in clan tag

### ISSUE THREAD

**Issue by baticag** [RoinujNosde/SimpleClans#60]
Players are using formatting codes that are not colors in their clan tags.
We need a way to deny that.
Thank you in advance!

**Comment by RoinujNosde** [comment]
Put those codes in ```disallowed-tag-colors```.

**Comment by SrBedrock** [comment]
Example:
```yml
  disallowed-tag-colors:
  - '4'
  - k
  - m
  - n
  - o
  - r
```
