### ISSUE TITLE
Configuração teleport-blocks não desativa ao usar /clan regroup

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/SimpleClans#67]
**Describe the bug**
A opção na config `teleport-blocks: false` funciona apenas para o comando `/clan base`, ao usar `/clan regroup base` ou `/clan regroup me` continua spawnando vidros ao reagrupar.

**To Reproduce**
1. Abra o arquivo `config.yml` e desative a opção `teleport-blocks`.
```yml
settings:
  teleport-blocks: false
```
2. Reinicie o servidor ou recarregue com `/clan reload`.
3. Use o comando `/clan regroup base` ou `/clan regroup me`.
4. Veja o spawn de blocos ao ser regrupado.

**Expected behavior**
Não spawnar vidros ao regrupar após desativar essa opção

**Screenshots**
![image](https://user-images.githubusercontent.com/51332006/97044844-18ef5280-154b-11eb-98da-53a955779f85.png)

**Software (please complete the following information):**
 - Server: Paper 1.16.3
 - Plugin version: 1.14.1

**Additional context**
Acho que poderia remover por completo essa função do plugin.

**Comment by RoinujNosde** [comment]
Corrigido na última build.
