### ISSUE TITLE
What the hell are these default permissions? you have caused havoc!

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#70]
Why did you add default permissions? Now I have crews able to somehow toggle if some people can be hurt and others cant? WITHOUT a message in chat!?
I have just wasted like 2 hours trying to figure out why some people can not be hurt and some can all of a sudden, there are no messages in chat for it.

Also, This should not be forced on to allow crew members to toggle friendly fire?

What permissions did you automatically add to people? No permissions should be automatically added to people...Now I have NO IDEA what you gave them access to?

Wait so, now do I have to somehow figure out what you added to everyone, and figure out what the permission is and disable it per group? this is backwards logic! 

I do not want crews being able to turn on/off friendly fire this never made any sence in the first place as there is no feedback!

**Comment by xtomyserrax** [comment]
Who do you think you are? Show some respect. This plugin is made for free so instead of demanging ask politely and say thanks to a guy who is using his free time to make an amazing plugin.

**Comment by TomLewis** [comment]
> 
> 
> Who do you think you are? Show some respect. This plugin is made for free so instead of demanging ask politely and say thanks to a guy who is using his free time to make an amazing plugin.

Who the hell do you think you are? How dare you act like keyboard warrior like you are some elite being, your reply is not helpful, it also TAKES THE CONVERSATION AWAY from the point of the conversation. I don't care what you think, do not reply to me, this is not your ticket. **DO NOT take this off topic.** 

I am having to go into Damage control, this update Randomly gave access to things specifically people should not have on my server, without warning, this is very damaging, Allowing peolpe to randomly turn off their PVP for themselves or their crew? Randomly allowing everyone on my server to enable crew fees, this is such a bad decision.
