### ISSUE TITLE
No longer use color when creating a Clan Rank. "You cannot set colored ranks"

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#80]
**Describe the bug**
When creating a rank, you can no longer set a color for the rank it says "You cannot set colored ranks" I cannot seem to find the permission node for it? The only thing I can find is ```simpleclans.leader.rank.setdisplayname``` I cant see a ```simpleclans.leader.rank.setdisplayname.colored``` 

Edit: tried it as OP, still gives the error.

https://simpleclans.gitbook.io/simpleclans/commands-and-permissions/permissions

**To Reproduce**
So you create a new crew rank with;
```/clan rank create KingRank```
Then you set its color with;

```/clan rank setdisplayname KingRank &cKing Rank```

And it displays "_You cannot set colored ranks"_

**Expected behavior**
To be able to set a crew rank color with the correct permission (And deny the use of the random character!)

**Software (please complete the following information):**
 - Server: Paper 1.12.2
 - Plugin version: 2.14.2

**Comment by RoinujNosde** [comment]
Try this one:
simpleclans.leader.coloredrank

Did you deny it?
It was default true since its implementation.

**Comment by TomLewis** [comment]
This worked!
Yes denied default as I have a ranking system that you inherit permissions, I dont want alts spamming by creating crews etc.

I tried as OP, didnt work and I couldnt see that permission in the docs! So it must be missing!
Thanks.
