### ISSUE TITLE
Admin Command /clan demote <leader> will only work on leaders in THEIR crew, not globally.

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/SimpleClans#81]
We have admins that need to be able to demote leaders from other crews, they have the permission 'simpleclans.admin.demote' but `/clan demote [leader]` tells them the player is not in their clan.
Im not sure if you changed the command for admins as admin commands are missing from https://simpleclans.gitbook.io/simpleclans/commands-and-permissions/commands

**Comment by RoinujNosde** [comment]
The demote and promote commands for admins have changed.
https://simpleclans.gitbook.io/simpleclans/commands-and-permissions/commands#admin-commands (just updated)
