### ISSUE TITLE
CreateClanEvent should be cancellable

### ISSUE THREAD

**Issue by bloodmc** [RoinujNosde/SimpleClans#87]
I'm currently adding support of SimpleClans to GriefDefender and need the ability to cancel CreateClanEvent.  

It also would help if you could pass the player creating the clan. Currently, I have to grab the player from `event.getClan().getOnlineLeaders()`.

**Comment by RoinujNosde** [comment]
I think that making this event cancellable could break the logic of plugins already listening to it.

Adding a cancellable PreCreateClanEvent would be safer.

**Comment by bloodmc** [comment]
Works for me. Can you also pass the source in this new event?

Thanks!
