### ISSUE TITLE
Clan banner is not saved

### ISSUE THREAD

**Issue by xtomyserrax** [RoinujNosde/SimpleClans#90]
Hey, I noticed that the /clan setbanner command works perfectly but after plugin reload (or server reload) your clan banner will turn back to default

**Comment by RoinujNosde** [comment]
Any steps to reproduce?

**Comment by xtomyserrax** [comment]
Basicly set a bannter with /clan setbanner and you will see that it has been changed, then /clan reload and the banner is back to default

**Comment by RoinujNosde** [comment]
@xtomyserrax only on /clan reload?
Or restart as well?

**Comment by xtomyserrax** [comment]
Server restart too. Ill send a video if you want

**Comment by RoinujNosde** [comment]
@xtomyserrax mysql or sqlite?

**Comment by xtomyserrax** [comment]
SQLite in my test server, but in CraftersLand I think they use MySQL and it also happens there (we are using latest spigot version)

**Comment by RoinujNosde** [comment]
It's happening here too, using 1.14.4
